// HU #12081 / #12083 — La FOTO HISTÓRICA pre-reconducción: qué roles exigía cada `requireRole` de los
// ficheros del alcance del Feature #12072 el día en que dejó de decidir (9/09/2026, 217 rutas leídas
// por el lector de la #12081; 11 más añadidas a mano por la #12083).
//
// Ya NO se genera: desde la #12083 esas rutas llevan `exigirFuncion('<codigo>')` y regenerarla desde
// el fuente la vaciaría (o, desde el código nuevo, la haría circular). Es la fuente de «antes» del test
// de paridad (AC7 de la #12083) y de `repartoDePartida()`, que es lo que la 0179 y la 0181 sembraron.
//
// SE EDITA A MANO SOLO para añadir funciones nuevas JUNTO CON SU MIGRACIÓN: una entrada aquí sin fila
// en `permisos_funciones` la ve `verificarCatalogoAlArrancar`; una fila allí sin entrada aquí, también.
// `permisos-catalogo.test.ts` comprueba que los montajes del fuente cubren exactamente esta foto.
import type { GuardaLeida } from './inventario-guardas.js';

/** 217 rutas guardadas medidas el 9/09/2026 + 11 añadidas por la HU #12083 (dos en línea); +2 −1 por la HU #12373 (tarifas); +2 por la HU #12171; +7 por la HU #12084 (permisos); +4 por la HU #12541 (servicios adicionales); +1 por la HU #12591 (recibo de caja); +5 por la HU #12611 (comprobantes); +3 por la HU #12619 (viajes de logística); +3 por la HU #12629 (comprobantes F2: buscar, aplicar, descartar); +1 por la HU #12654 (comprobantes F3: aceptar diferencia); +2 por el Bug #12642 (export ampliado con datos de pago, dos en línea); +1 por la HU #12833 (corregir dirección del comprador); +2 por la HU #12997 (incompletas SOAT: buscar y ver); +1 por la HU #12998 (reintentar la consulta RUNT de una incompleta); +2 por la HU #13061 (acceso a FLIT 2: ver y guardar); +1 por la HU #13237 (interruptor de sincronización por fuente); +1 por la HU #13269 (reemplazar el comprobante de pago, sin rol); +1 por la HU #13362 (documentos adicionales del SOAT); +76 por la HU #13421 (pesv, drivers, jornadas y rum legacy); +1 por la HU #13425 (operar actas ajenas, en línea); +3 por la HU #13425 fase B (jornada ajena y vista de auditoría del diagnóstico, en línea); +92 por la HU #13422 (maintenance 33, vehicles 12 + 1 en línea, fleet 10, rndc 5, rutas 16, liquidacion 4, finanzas 8, clients 3); +134 por la HU #13423 (laft 60, siigo 35 + 8 en línea, soat 12, drive 6, privacy 4, firma 2, vehicles 4, runt 2, integraciones 1); +1 por la HU #12874 (compañías del canal SOAT sin trámite, reutiliza `soat.solicitud.crear`). */
export const GUARDAS_MEDIDAS: GuardaLeida[] = [
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/export", roles: ["admin","proveedor"], heredada: false },
  // Bug #12642: la guarda EN LÍNEA del archivo ampliado (`incluirPago: true`), sembrada por la 0203 SOLO a admin.
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/export", condicion: "incluirPago", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/soportes/zip", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "GET", ruta: "/facetas", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "GET", ruta: "/:id/historial", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "GET", ruta: "/:id/soportes", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/enviar", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/rechazar", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/reactivar", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/reversar", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/proveedor", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/asumir-operaciones", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/devolver-gestor", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/:id/factura", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat.routes.ts", metodo: "POST", ruta: "/facturas", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-cliente.routes.ts", metodo: "POST", ruta: "/cliente/preconsulta", roles: ["cliente"], heredada: false },
  // HU #12874: la lista de compañías del formulario reutiliza `soat.solicitud.crear` (sin función nueva
  // ni migración, decisión del PO); mismos roles de partida que el alta, así que el reparto no cambia.
  { modulo: "soat", fichero: "flito-soat/flito-soat-cliente.routes.ts", metodo: "GET", ruta: "/cliente/companias", roles: ["cliente"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-cliente.routes.ts", metodo: "POST", ruta: "/cliente", roles: ["cliente"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-cliente.routes.ts", metodo: "POST", ruta: "/cliente/factura/lectura", roles: ["cliente"], heredada: false },
  // HU #12997: lectura de las incompletas por RUNT caído; mismos roles de partida que `GET /` y `GET /:id` (0211).
  { modulo: "soat", fichero: "flito-soat/flito-soat-incompletas.routes.ts", metodo: "POST", ruta: "/cliente/incompletas/buscar", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-incompletas.routes.ts", metodo: "GET", ruta: "/cliente/incompletas/:id", roles: ["admin","auditor","cliente","proveedor"], heredada: false },
  // HU #12998: la acción de reintentar; de partida solo admin (0212, P-8).
  { modulo: "soat", fichero: "flito-soat/flito-soat-incompletas.routes.ts", metodo: "POST", ruta: "/cliente/incompletas/:id/reintentar", roles: ["admin"], heredada: false },
  // HU #13362 (0222): documentos adicionales de una solicitud — operación FLIT y proveedor SOAT; el cliente NO.
  { modulo: "soat", fichero: "flito-soat/flito-soat-documentos.routes.ts", metodo: "GET", ruta: "/:id/documentos-adicionales", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-documentos.routes.ts", metodo: "POST", ruta: "/:id/documentos-adicionales", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "flito-soat/flito-soat-documentos.routes.ts", metodo: "DELETE", ruta: "/:id/documentos-adicionales/:soporteId", roles: ["admin","proveedor"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/:id/factura-venta", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/soportes/zip", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/export", roles: ["admin","gestor_impuestos"], heredada: false },
  // Bug #12642: la guarda EN LÍNEA del archivo ampliado (`incluirPago: true`), sembrada por la 0203 SOLO a admin.
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/export", condicion: "incluirPago", roles: ["admin"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/facetas", roles: ["admin","auditor","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","auditor","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/:id/historial", roles: ["admin","auditor","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/:id/soportes", roles: ["admin","auditor","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/certificar", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/certificar", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "GET", ruta: "/:id/certificado", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/enviar", roles: ["admin"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/rechazar", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/reactivar", roles: ["admin"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/reversar", roles: ["admin"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/recibos", roles: ["admin","gestor_impuestos"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/recibo-caja", roles: ["admin"], heredada: false },
  // HU #12833: sembrada por la 0208 SOLO a admin.
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.direccion.routes.ts", metodo: "PATCH", ruta: "/:id/direccion", roles: ["admin"], heredada: false },
  // HU #13269: la 0220 la siembra SIN reparto (AC7): ningún rol de partida.
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.recibo-reemplazo.routes.ts", metodo: "POST", ruta: "/:id/recibos/reemplazar-pago", roles: [], heredada: false },
  // HU #12083: las dos rutas del `for` con template literal que el lector de la #12081 no vio.
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/asumir-operaciones", roles: ["admin"], heredada: false },
  { modulo: "impuestos", fichero: "flito-impuestos/flito-impuestos.routes.ts", metodo: "POST", ruta: "/:id/devolver-gestor", roles: ["admin"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "POST", ruta: "/cargar", roles: ["admin"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/facetas", roles: ["admin","auditor"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/drive/archivos", roles: ["admin","auditor"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/drive/registro", roles: ["admin","auditor"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "POST", ruta: "/drive/procesar", roles: ["admin"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/candidatos/:placa", roles: ["admin","auditor"], heredada: false },
  { modulo: "derechos", fichero: "flito-derechos/flito-derechos.routes.ts", metodo: "GET", ruta: "/soporte/:id", roles: ["admin","auditor"], heredada: false },
  { modulo: "revisiones", fichero: "flito-revisiones/flito-revisiones.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "revisiones", fichero: "flito-revisiones/flito-revisiones.routes.ts", metodo: "GET", ruta: "/campos/:modulo", roles: ["admin","auditor"], heredada: false },
  { modulo: "revisiones", fichero: "flito-revisiones/flito-revisiones.routes.ts", metodo: "GET", ruta: "/soporte/:soporteId/archivo", roles: ["admin","auditor"], heredada: false },
  { modulo: "revisiones", fichero: "flito-revisiones/flito-revisiones.routes.ts", metodo: "POST", ruta: "/:id/resolver", roles: ["admin"], heredada: false },
  { modulo: "revisiones", fichero: "flito-revisiones/flito-revisiones.routes.ts", metodo: "POST", ruta: "/:id/descartar", roles: ["admin"], heredada: false },
  { modulo: "compuerta", fichero: "flito-compuerta/flito-compuerta.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "compuerta", fichero: "flito-compuerta/flito-compuerta.routes.ts", metodo: "GET", ruta: "/:tramiteId", roles: ["admin","auditor"], heredada: false },
  { modulo: "compuerta", fichero: "flito-compuerta/flito-compuerta.routes.ts", metodo: "POST", ruta: "/:tramiteId/entregar", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "GET", ruta: "/facetas", roles: ["admin","auditor"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "GET", ruta: "/:id/historial", roles: ["admin","auditor"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "GET", ruta: "/:id/soportes", roles: ["admin","auditor"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/soportes/zip", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/crear-empresa", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/demo", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/solicitar-soat", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/solicitar-impuestos", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/solicitar-ambos", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/entregar", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/:id/desbloquear-autogestion", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-tramites/flito-tramites.routes.ts", metodo: "POST", ruta: "/:id/revocar-autogestion", roles: ["admin"], heredada: false },
  { modulo: "tablero", fichero: "flito-tablero/flito-tablero.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "bitacora", fichero: "flito-bitacora/flito-bitacora.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "bitacora", fichero: "flito-bitacora/flito-bitacora.routes.ts", metodo: "GET", ruta: "/:resource/:resourceId", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/facetas", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/mi-ruta", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/actas", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/actas/:id", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/actas/:id/pdf", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","auditor"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/validar-lt", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/escanear", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/documentos/:id/novedad", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/cerrar-lote", roles: ["admin"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/actas/:id/despachar", roles: ["admin"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/actas/:id/entregar", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/actas/:id/entregar", condicion: "operarAjenas", roles: ["admin"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/actas/:id/devolucion", roles: ["admin","mensajero"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica.routes.ts", metodo: "POST", ruta: "/documentos/:id/reversar", roles: ["admin"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/consolidado", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/riesgo", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/alertas", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/transito", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/transito", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/:companiaId", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/:companiaId/movimientos", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/:companiaId/recargas", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/soportes/:soporteId", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/transito/:bolsaId", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "PATCH", ruta: "/transito/:bolsaId", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/transito/:bolsaId/movimientos", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/transito/:bolsaId/cargas", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/:companiaId/extracto", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/:companiaId/movimientos-manuales", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/:companiaId/movimientos/:movimientoId/correccion", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "GET", ruta: "/:companiaId/cierres", roles: ["admin","financiera"], heredada: false },
  { modulo: "bolsas", fichero: "flito-bolsas/flito-bolsas.routes.ts", metodo: "POST", ruta: "/:companiaId/cierres", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "POST", ruta: "/boletas", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "GET", ruta: "/boletas", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "GET", ruta: "/boletas/:id", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "POST", ruta: "/boletas/:id/recruzar", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "POST", ruta: "/boletas/:id/conciliar", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "POST", ruta: "/boletas/:id/descartar", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "POST", ruta: "/boletas/:id/comprobante", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "PUT", ruta: "/boletas/:id/comprobante", roles: ["admin","financiera"], heredada: false },
  { modulo: "conciliacion", fichero: "flito-conciliacion/flito-conciliacion.routes.ts", metodo: "GET", ruta: "/boletas/:id/comprobante", roles: ["admin","financiera"], heredada: false },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/nits", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/nits", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "PATCH", ruta: "/nits/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "DELETE", ruta: "/nits/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/municipios", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/municipios", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "PATCH", ruta: "/municipios/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/causales", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/causales", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "PATCH", ruta: "/causales/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/config/token-simit", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "PUT", ruta: "/config/token-simit", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/sync", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/sync/runs", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/sync/runs/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/registros", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/registros/buscar", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "POST", ruta: "/registros/export", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/registros/:id", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "GET", ruta: "/registros/:id/eventos", roles: ["admin"], heredada: true },
  { modulo: "comparendos", fichero: "flito-comparendos/flito-comparendos.routes.ts", metodo: "PATCH", ruta: "/registros/:id/gestion", roles: ["admin"], heredada: true },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "GET", ruta: "/:tramiteId", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "GET", ruta: "/:tramiteId/eventos", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "POST", ruta: "/:tramiteId/liquidar", roles: ["admin","financiera"], heredada: false },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "POST", ruta: "/lote/liquidar", roles: ["admin","financiera"], heredada: false },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "POST", ruta: "/:tramiteId/reversar", roles: ["admin"], heredada: false },
  { modulo: "liquidacion", fichero: "flito-liquidacion/flito-liquidacion.routes.ts", metodo: "POST", ruta: "/:tramiteId/facturar", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/companias", roles: ["admin","auditor"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "PATCH", ruta: "/companias/:id", roles: ["admin"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/proveedores-soat", roles: ["admin","auditor"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "POST", ruta: "/proveedores-soat", roles: ["admin"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "PATCH", ruta: "/proveedores-soat/:id", roles: ["admin"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/organismos", roles: ["admin","auditor"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/organismos/:codigo/vigencias", roles: ["admin","auditor"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "POST", ruta: "/organismos/:codigo/modalidad", roles: ["admin"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "PATCH", ruta: "/organismos/:codigo", roles: ["admin"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/tarifas", roles: ["admin","financiera"], heredada: false }, // HU #12373: el auditor deja de ver tarifas
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "POST", ruta: "/tarifas", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "PATCH", ruta: "/tarifas/:id", roles: ["admin","financiera"], heredada: false },
  // HU #12373: DELETE /tarifas/:id retirada (una vigencia se cierra, no se borra); +2 GET nuevas.
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/tarifas/companias/:id", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/tarifas/companias/:id/historial", roles: ["admin","financiera"], heredada: false },
  // HU #12541: catálogo de tipos de servicio adicional; mismo reparto que las tarifas (admin + financiera).
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "GET", ruta: "/servicios-adicionales", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "POST", ruta: "/servicios-adicionales", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "PATCH", ruta: "/servicios-adicionales/:id", roles: ["admin","financiera"], heredada: false },
  { modulo: "parametrizacion", fichero: "flito-parametrizacion/flito-parametrizacion.routes.ts", metodo: "POST", ruta: "/servicios-adicionales/:id/baja", roles: ["admin","financiera"], heredada: false },
  { modulo: "sync", fichero: "flito-sync/flito-sync.routes.ts", metodo: "GET", ruta: "/estado", roles: ["admin"], heredada: false },
  { modulo: "sync", fichero: "flito-sync/flito-sync.routes.ts", metodo: "POST", ruta: "/sincronizar", roles: ["admin"], heredada: false },
  // HU #13061: acceso de FLITO a FLIT 2 (módulo tramites); de partida solo admin (0214).
  { modulo: "tramites", fichero: "flito-sync/flit2.routes.ts", metodo: "GET", ruta: "/acceso", roles: ["admin"], heredada: false },
  { modulo: "tramites", fichero: "flito-sync/flit2.routes.ts", metodo: "PUT", ruta: "/acceso", roles: ["admin"], heredada: false },
  // HU #13237: interruptor por fuente (0217, solo admin). El GET /interruptores reutiliza el código.
  { modulo: "tramites", fichero: "flito-sync/flito-sync-interruptores.routes.ts", metodo: "PUT", ruta: "/interruptores/:fuente", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/tipologias", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/motivos-rechazo-ot", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/embudo", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/notif-config", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/metrics/summary", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/metrics/gestor", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/lote/plantilla.csv", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/lote/preview", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/lote", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/lote/async", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/lote/confirm", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/lote", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/lote/:id/estado", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/lote/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/lote/:id/reprocesar-errores", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/lote/:id/resultados.csv", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/preflight", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/impuesto-vehicular/consultar", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/stats/metricas", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/stats/resumen", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/checklist", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/checklist/sugerir", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/preflight", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/preflight/cta", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/rechazar-ot", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/timeline", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/invitar", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/participantes-pendientes", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/expediente.pdf", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/verify-token", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "PATCH", ruta: "/:id/estado", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","transito"], heredada: true },
  // HU #12083: la guarda EN LÍNEA de `_forzarContinuar` (`role !== 'admin'` dentro del handler).
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "PATCH", ruta: "/:id", condicion: "_forzarContinuar", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/documentos", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:id/documentos", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "GET", ruta: "/:tramiteId/documentos/:docId/archivo", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "DELETE", ruta: "/:tramiteId/documentos/:docId", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/generar-fur", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/generar-contrato", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/tramites.routes.ts", metodo: "POST", ruta: "/:id/generar-improntas", roles: ["admin","transito"], heredada: true },
  { modulo: "tramite", fichero: "tramites/ocr-docs.routes.ts", metodo: "POST", ruta: "/ocr/:tipo", roles: ["admin"], heredada: true },
  { modulo: "tramite", fichero: "tramites/ocr-docs.routes.ts", metodo: "GET", ruta: "/ocr-extracted/:filename", roles: ["admin"], heredada: true },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "GET", ruta: "/sse", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "POST", ruta: "/iniciar", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "POST", ruta: "/iniciar-partes", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "GET", ruta: "/estado/:tramiteId", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "GET", ruta: "/documentos/:tramiteId", roles: ["admin"], heredada: false },
  { modulo: "tramite", fichero: "tramites/identidad.routes.ts", metodo: "POST", ruta: "/certificado/:tramiteId", roles: ["admin"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "GET", ruta: "/organismos", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "GET", ruta: "/pendientes", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "GET", ruta: "/mis-tramites", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "GET", ruta: "/traspasos", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "GET", ruta: "/traspasos/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "POST", ruta: "/tomar/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "POST", ruta: "/asignar-placa/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito.routes.ts", metodo: "POST", ruta: "/confirmar-placa/:id", roles: ["admin","transito"], heredada: true },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "GET", ruta: "/organismos-config", roles: ["admin"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "GET", ruta: "/organismos-config/:codigo", roles: ["admin","transito"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "GET", ruta: "/organismos-config/:codigo/checklist/:tipologia", roles: ["admin","transito"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "PUT", ruta: "/organismos-config/:codigo/checklist/:tipologia", roles: ["admin"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "PUT", ruta: "/organismos-config/:codigo", roles: ["admin"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "GET", ruta: "/organismos-config/:codigo/logo", roles: ["admin","transito"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "POST", ruta: "/organismos-config/:codigo/logo", roles: ["admin"], heredada: false },
  { modulo: "transito", fichero: "tramites/transito-config.routes.ts", metodo: "DELETE", ruta: "/organismos-config/:codigo/logo", roles: ["admin"], heredada: false },
  // HU #12083: `users/` no estaba en el alcance de la #12081. Siete rutas heredaban
  // `router.use(authMiddleware, requireRole de admin)`; la contraseña ajena era `role !== 'admin'` en línea.
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "PATCH", ruta: "/:id/password", condicion: "ajena", roles: ["admin"], heredada: false },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "GET", ruta: "/export", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "GET", ruta: "/resumen", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "PATCH", ruta: "/:id/toggle", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "POST", ruta: "/:id/reactivar", roles: ["admin"], heredada: false },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "POST", ruta: "/:id/invalidate-sessions", roles: ["admin"], heredada: true },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "GET", ruta: "/auditoria", roles: ["admin","auditor"], heredada: false },
  { modulo: "usuarios", fichero: "users/users.routes.ts", metodo: "GET", ruta: "/auditoria/titulares", roles: ["admin","auditor"], heredada: false },
  // HU #12084 — permisos/: `GET /funciones` llevaba `requireRole` de admin; las seis restantes nacen con la HU (solo admin).
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "GET", ruta: "/funciones", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "GET", ruta: "/roles", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "POST", ruta: "/roles", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "PATCH", ruta: "/roles/:codigo", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "DELETE", ruta: "/roles/:codigo", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "GET", ruta: "/roles/:codigo/funciones", roles: ["admin"], heredada: false },
  { modulo: "permisos", fichero: "permisos/permisos.routes.ts", metodo: "PUT", ruta: "/roles/:codigo/funciones", roles: ["admin"], heredada: false },
  // HU #12545: servicios adicionales por trámite (+3). `ver` con el alcance de LECTURA del reporte
  // (admin, auditor, financiera); asignar/quitar solo admin y financiera.
  { modulo: "finanzas", fichero: "finanzas-servicios-adicionales/finanzas-servicios-adicionales.routes.ts", metodo: "GET", ruta: "/tramites/:id/servicios-adicionales", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas-servicios-adicionales/finanzas-servicios-adicionales.routes.ts", metodo: "POST", ruta: "/tramites/:id/servicios-adicionales", roles: ["admin","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas-servicios-adicionales/finanzas-servicios-adicionales.routes.ts", metodo: "DELETE", ruta: "/tramites/:id/servicios-adicionales/:asignacionId", roles: ["admin","financiera"], heredada: false },
  // HU #12611: las cinco de la puerta universal de comprobantes (F1 #12605), sembradas por la 0198 a admin + financiera.
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "GET", ruta: "/:id/archivo", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/:id/releer", roles: ["admin","financiera"], heredada: false },
  // HU #12629: las tres de F2 #12606 (buscar trámites, aplicar, descartar), sembradas por la 0201 a admin + financiera.
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/tramites/buscar", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/:id/aplicar", roles: ["admin","financiera"], heredada: false },
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/:id/descartar", roles: ["admin","financiera"], heredada: false },
  // HU #12654: aceptar la diferencia de un comprobante (F3 #12607), sembrada por la 0202 a admin + financiera.
  { modulo: "comprobantes", fichero: "flito-comprobantes/flito-comprobantes.routes.ts", metodo: "POST", ruta: "/:id/diferencia/aceptar", roles: ["admin","financiera"], heredada: false },
  // HU #12619: viajes adicionales de logística por trámite (+3), sembradas por la 0199 SOLO a admin
  // (el administrador reparte a los demás roles desde el panel).
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica-viajes.routes.ts", metodo: "GET", ruta: "/tramites/:tramiteId/viajes", roles: ["admin"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica-viajes.routes.ts", metodo: "POST", ruta: "/tramites/:tramiteId/viajes", roles: ["admin"], heredada: false },
  { modulo: "logistica", fichero: "flito-logistica/flito-logistica-viajes.routes.ts", metodo: "DELETE", ruta: "/tramites/:tramiteId/viajes/:viajeId", roles: ["admin"], heredada: false },
  // HU #13421 (ADR-0023): las 76 guardas `requireRole` de pesv/ (48), drivers/ (24), jornadas/ (3) y rum/ (1)
  // el día que dejaron de decidir (develop 29d3461e). `roles` = la lista literal de su `requireRole`, que es
  // también el reparto de su código: las guardas que comparten código tienen la misma lista (ver
  // catalogo-operaciones.legado.ts). Sembradas por la 0227.
  { modulo: "pesv", fichero: "pesv/export.routes.ts", metodo: "POST", ruta: "/sisi", roles: ["admin"], heredada: false },
  { modulo: "pesv", fichero: "pesv/export-diagnostico.routes.ts", metodo: "GET", ruta: "/diagnostico/:id/estandar/:codigo", roles: ["admin","compliance","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/export-diagnostico.routes.ts", metodo: "GET", ruta: "/diagnostico/:id", roles: ["admin","compliance","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "PATCH", ruta: "/:id/items/:estandarId", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "GET", ruta: "/:id/preflight", roles: ["admin","compliance","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "POST", ruta: "/:id/cerrar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "GET", ruta: "/:id/items/:estandarId/historial", roles: ["admin","compliance","lider_pesv"], heredada: false },
  // HU #13425: las dos guardas EN LÍNEA del detalle (antes, por nombre de rol): abrir la vista de auditoría y sugerirla al que solo consulta.
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "GET", ruta: "/:id", condicion: "vistaAuditoria", roles: ["admin","compliance","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico.routes.ts", metodo: "GET", ruta: "/:id", condicion: "sugerirAuditoria", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico-evidencias.routes.ts", metodo: "POST", ruta: "/:id/items/:estandarId/evidencias", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico-evidencias.routes.ts", metodo: "DELETE", ruta: "/:id/items/:estandarId/evidencias/:keyHash", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/diagnostico-evidencias.routes.ts", metodo: "GET", ruta: "/:id/items/:estandarId/evidencias/:keyHash", roles: ["admin","compliance","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "POST", ruta: "/:id/miembros", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "DELETE", ruta: "/:id/miembros/:userId", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "POST", ruta: "/:id/actas", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "PATCH", ruta: "/:id/actas/:actaId", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/comite.routes.ts", metodo: "POST", ruta: "/:id/actas/:actaId/cerrar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "POST", ruta: "/:id/aprobar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "POST", ruta: "/:id/objetivos", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "POST", ruta: "/objetivos/:objId/acciones", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/plan.routes.ts", metodo: "PATCH", ruta: "/acciones/:accId", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/policy.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/policy.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/policy.routes.ts", metodo: "POST", ruta: "/:id/firmar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/policy.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/auditorias", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/auditorias/:id/cerrar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/auditorias/:id/hallazgos", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/hallazgos/:hallazgoId/cerrar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/comunicaciones", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/comunicaciones/:id/publicar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "POST", ruta: "/contratistas", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "PATCH", ruta: "/contratistas/:id", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/huerfanos.routes.ts", metodo: "PATCH", ruta: "/incidents/:id/causa-raiz", roles: ["admin","lider_pesv","supervisor_flota"], heredada: false },
  { modulo: "pesv", fichero: "pesv/raci.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/raci.routes.ts", metodo: "PATCH", ruta: "/:id(\\\\d+)", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/raci.routes.ts", metodo: "DELETE", ruta: "/:id(\\\\d+)", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/raci.routes.ts", metodo: "PUT", ruta: "/proceso", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/normativa.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/normativa.routes.ts", metodo: "PATCH", ruta: "/:id(\\\\d+)", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/normativa.routes.ts", metodo: "POST", ruta: "/:id(\\\\d+)/revisar", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/normativa.routes.ts", metodo: "DELETE", ruta: "/:id(\\\\d+)", roles: ["admin"], heredada: false },
  { modulo: "pesv", fichero: "pesv/retencion.routes.ts", metodo: "POST", ruta: "/politicas", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/retencion.routes.ts", metodo: "PATCH", ruta: "/politicas/:id(\\\\d+)", roles: ["admin","lider_pesv"], heredada: false },
  { modulo: "pesv", fichero: "pesv/retencion.routes.ts", metodo: "DELETE", ruta: "/politicas/:id(\\\\d+)", roles: ["admin"], heredada: false },
  { modulo: "pesv", fichero: "pesv/retencion.routes.ts", metodo: "POST", ruta: "/run", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/drivers.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/drivers.routes.ts", metodo: "PATCH", ruta: "/:id/profile", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/drivers.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/drivers.routes.ts", metodo: "GET", ruta: "/candidates/non-driver", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/documents.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/documents.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/documents.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/trainings.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/trainings.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/trainings.routes.ts", metodo: "POST", ruta: "/:id/attendees", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/trainings.routes.ts", metodo: "PATCH", ruta: "/:id/attendees/:userId", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/incidents.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","lider_pesv","supervisor_flota"], heredada: false },
  { modulo: "drivers", fichero: "drivers/incidents.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/incidents.routes.ts", metodo: "POST", ruta: "/:id/actions", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/incidents.routes.ts", metodo: "PATCH", ruta: "/:id/actions/:actionId", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/incidents.routes.ts", metodo: "POST", ruta: "/:id/close", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/checklists.routes.ts", metodo: "POST", ruta: "/:id/anular", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/alcohol.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/alcohol.routes.ts", metodo: "POST", ruta: "/:id/levantar-suspension", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/emergency.routes.ts", metodo: "POST", ruta: "/contacts", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/emergency.routes.ts", metodo: "PATCH", ruta: "/contacts/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/emergency.routes.ts", metodo: "DELETE", ruta: "/contacts/:id", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/emergency.routes.ts", metodo: "POST", ruta: "/protocols", roles: ["admin"], heredada: false },
  { modulo: "drivers", fichero: "drivers/emergency.routes.ts", metodo: "POST", ruta: "/drills", roles: ["admin"], heredada: false },
  { modulo: "jornadas", fichero: "jornadas/jornadas.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "jornadas", fichero: "jornadas/jornadas.routes.ts", metodo: "POST", ruta: "/alarmas/:alarmaId/ack", roles: ["admin"], heredada: false },
  { modulo: "jornadas", fichero: "jornadas/jornadas.routes.ts", metodo: "POST", ruta: "/reporte-mensual/regenerar", roles: ["admin"], heredada: false },
  // HU #13425: la guarda EN LÍNEA «jornada de otro conductor» (`operaJornadaAjena`, antes `role !== 'admin'`), una para las 6 rutas.
  { modulo: "jornadas", fichero: "jornadas/jornadas.routes.ts", metodo: "POST", ruta: "/abrir", condicion: "jornadaAjena", roles: ["admin"], heredada: false },
  { modulo: "rum", fichero: "rum/rum.routes.ts", metodo: "GET", ruta: "/summary", roles: ["admin"], heredada: false },
  // HU #13422 (ADR-0023): las guardas `requireRole` de maintenance/, vehicles/, fleet/, rndc/, rutas/,
  // liquidacion/, finanzas/ y clients/ el día que dejaron de decidir (develop 8f0d8b85). `roles` = la lista
  // literal de su `requireRole` (o del `router.use(requireRole)` que las cubría: `heredada: true`). Las de
  // `LECTURA` de finanzas y clients exigían admin, auditor y financiera. Sembradas por la 0229.
  { modulo: "maintenance", fichero: "maintenance/catalog.routes.ts", metodo: "POST", ruta: "/systems", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/catalog.routes.ts", metodo: "POST", ruta: "/subsystems", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/catalog.routes.ts", metodo: "POST", ruta: "/jobs", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/catalog.routes.ts", metodo: "PATCH", ruta: "/jobs/:id", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/catalog.routes.ts", metodo: "PATCH", ruta: "/mechanics/:userId", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "POST", ruta: "/:id/jobs", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "DELETE", ruta: "/:id/jobs/:jobId", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "POST", ruta: "/:id/parts", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "DELETE", ruta: "/:id/parts/:partId", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "POST", ruta: "/:id/periodicity", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/routines.routes.ts", metodo: "DELETE", ruta: "/:id/periodicity/:periodId", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/schedule.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/schedule.routes.ts", metodo: "PATCH", ruta: "/:id/cancel", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/schedule.routes.ts", metodo: "POST", ruta: "/recompute", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/parts.routes.ts", metodo: "POST", ruta: "/locations", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/parts.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/parts.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/parts.routes.ts", metodo: "POST", ruta: "/movements", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/preorders.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/preorders.routes.ts", metodo: "POST", ruta: "/:id/jobs", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/preorders.routes.ts", metodo: "POST", ruta: "/:id/parts", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/preorders.routes.ts", metodo: "POST", ruta: "/:id/approve", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/preorders.routes.ts", metodo: "POST", ruta: "/:id/generate-ot", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/jobs", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/parts", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/otros-gastos", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/seguimiento", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/close-tecnica", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/close-final", roles: ["admin"], heredada: false },
  { modulo: "maintenance", fichero: "maintenance/workorders.routes.ts", metodo: "POST", ruta: "/:id/anular", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "POST", ruta: "/upload", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/export", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "PATCH", ruta: "/:id/multas", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "PATCH", ruta: "/:id/stage", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "PATCH", ruta: "/:id/client", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/pipeline/stats", roles: ["admin"], heredada: false },
  // HU #13422: la guarda EN LÍNEA del documento completo del propietario en el listado (antes `role !== 'admin'`).
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/", condicion: "documentoCompleto", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/ocr.routes.ts", metodo: "POST", ruta: "/ocr", roles: ["admin"], heredada: true },
  { modulo: "vehicles", fichero: "vehicles/ocr.routes.ts", metodo: "POST", ruta: "/ocr-export", roles: ["admin"], heredada: true },
  { modulo: "vehicles", fichero: "vehicles/ocr.routes.ts", metodo: "POST", ruta: "/ocr-import", roles: ["admin"], heredada: true },
  { modulo: "fleet", fichero: "fleet/vehicles.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/vehicles.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/vehicles.routes.ts", metodo: "POST", ruta: "/:id/convert", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/links.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/links.routes.ts", metodo: "PATCH", ruta: "/:id/close", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/documents.routes.ts", metodo: "POST", ruta: "/types", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/documents.routes.ts", metodo: "PATCH", ruta: "/types/:id", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/documents.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/documents.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "fleet", fichero: "fleet/documents.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "rndc", fichero: "rndc/credenciales.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "rndc", fichero: "rndc/credenciales.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "rndc", fichero: "rndc/credenciales.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: true },
  { modulo: "rndc", fichero: "rndc/manifiestos.routes.ts", metodo: "POST", ruta: "/:id/encolar-envio", roles: ["admin"], heredada: false },
  { modulo: "rndc", fichero: "rndc/manifiestos.routes.ts", metodo: "POST", ruta: "/:id/reintentar-envio", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "POST", ruta: "/:id/waypoints", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "PATCH", ruta: "/waypoints/:wpId", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "DELETE", ruta: "/waypoints/:wpId", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/routes.routes.ts", metodo: "POST", ruta: "/:id/waypoints/reorder", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/risk.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/risk.routes.ts", metodo: "POST", ruta: "/:id/aprobar", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/risk.routes.ts", metodo: "POST", ruta: "/:id/items", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/risk.routes.ts", metodo: "PATCH", ruta: "/items/:itemId", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/risk.routes.ts", metodo: "DELETE", ruta: "/items/:itemId", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/pernocta.routes.ts", metodo: "POST", ruta: "/pernocta", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/pernocta.routes.ts", metodo: "PATCH", ruta: "/pernocta/:id", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/pernocta.routes.ts", metodo: "DELETE", ruta: "/pernocta/:id", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/pernocta.routes.ts", metodo: "POST", ruta: "/assignments", roles: ["admin"], heredada: false },
  { modulo: "rutas", fichero: "rutas/pernocta.routes.ts", metodo: "DELETE", ruta: "/assignments/:id", roles: ["admin"], heredada: false },
  { modulo: "liquidacion", fichero: "liquidacion/liquidacion.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "liquidacion", fichero: "liquidacion/liquidacion.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "liquidacion", fichero: "liquidacion/liquidacion.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin"], heredada: true },
  { modulo: "liquidacion", fichero: "liquidacion/liquidacion.routes.ts", metodo: "POST", ruta: "/:id/confirmar-pago", roles: ["admin"], heredada: true },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/reporte-costos", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/reporte-costos/facetas", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/reporte-costos/facturacion-electronica", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/reporte-costos/consolidado", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "POST", ruta: "/reporte-costos/export", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "POST", ruta: "/reporte-costos/consolidado/export", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/tramites/:id/soportes", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "finanzas", fichero: "finanzas/finanzas.routes.ts", metodo: "GET", ruta: "/tramites/:id/viajes-logistica", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "clients", fichero: "clients/clients.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "clients", fichero: "clients/clients.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "clients", fichero: "clients/clients.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  // HU #13423 (ADR-0023): laft/, privacy/, firma/, drive/, soat/ (antiguo) y siigo/ el día que dejaron de
  // decidir por rol (base a2b2cd47, HU #13422). `roles` = la lista literal de su guarda de rol (o de la
  // guarda de rol de su `router.use` que las cubría: `heredada: true`); en siigo/, la fila de cada acción en la
  // vieja tabla de roles por acción (guardas en línea de `siigo.permisos.ts`, una por acción). Las cuatro
  // operaciones que solo pedían sesión (vehicles, runt ×2, integraciones) llevan el reparto por defecto
  // de las páginas que las llaman: la 0230 las siembra como COPIA VIVA de esas páginas.
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "POST", ruta: "/:code/sync", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "POST", ruta: "/:code/upload-csv", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "POST", ruta: "/check/:counterpartyId", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "GET", ruta: "/checks/:counterpartyId", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/lists.routes.ts", metodo: "GET", ruta: "/entry/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/counterparties.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/counterparties.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/counterparties.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/counterparties.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/counterparties.routes.ts", metodo: "POST", ruta: "/:id/status", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/audit.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/trainings.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/trainings.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/trainings.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/trainings.routes.ts", metodo: "POST", ruta: "/:id/attendance", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/unusual.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/unusual.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/unusual.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/unusual.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/audit-plan/audit-plan.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","compliance"], heredada: false },
  { modulo: "laft", fichero: "laft/audit-plan/audit-plan.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin","compliance"], heredada: false },
  { modulo: "laft", fichero: "laft/audit-plan/audit-plan.routes.ts", metodo: "POST", ruta: "/:id/evidencia", roles: ["admin","compliance"], heredada: false },
  { modulo: "laft", fichero: "laft/audit-plan/audit-plan.routes.ts", metodo: "POST", ruta: "/:id/cerrar", roles: ["admin","compliance"], heredada: false },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "POST", ruta: "/from-operation/:opId", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "POST", ruta: "/:id/clasificar", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "POST", ruta: "/:id/sent", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "POST", ruta: "/:id/sirel-radicado", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/ros.routes.ts", metodo: "GET", ruta: "/sla/abiertos", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sirel/ros-export.routes.ts", metodo: "POST", ruta: "/:id/export", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sirel/ros-export.routes.ts", metodo: "GET", ruta: "/:id/export/pdf", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sirel/ros-export.routes.ts", metodo: "GET", ruta: "/:id/export/csv", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/aros.routes.ts", metodo: "POST", ruta: "/generar/:anio/:trimestre", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/aros.routes.ts", metodo: "GET", ruta: "/:anio/:trimestre/download", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/aros.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/rte.routes.ts", metodo: "POST", ruta: "/generar/:anio/:mes", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/rte.routes.ts", metodo: "GET", ruta: "/:anio/:mes/download", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/rte.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/cash.routes.ts", metodo: "POST", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/cash.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/cash.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/cash/cash.routes.ts", metodo: "PATCH", ruta: "/:id/link-ros", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "GET", ruta: "/:userId", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "POST", ruta: "/:userId/kyc", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "PATCH", ruta: "/:userId", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "POST", ruta: "/:userId/antecedentes", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/employees/employees.routes.ts", metodo: "POST", ruta: "/:userId/rekyc", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/manual/manual.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/manual/manual.routes.ts", metodo: "POST", ruta: "/:id/firmar", roles: ["admin","compliance"], heredada: false },
  { modulo: "laft", fichero: "laft/manual/manual.routes.ts", metodo: "POST", ruta: "/:id/publicar", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/retencion/retencion.routes.ts", metodo: "POST", ruta: "/anonimizar/:tipo", roles: ["admin"], heredada: true },
  { modulo: "laft", fichero: "laft/dashboard/dashboard.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sync/sync.routes.ts", metodo: "GET", ruta: "/jobs", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sync/sync.routes.ts", metodo: "GET", ruta: "/jobs/:id", roles: ["admin","compliance"], heredada: true },
  { modulo: "laft", fichero: "laft/sync/sync.routes.ts", metodo: "POST", ruta: "/run/:listCode", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/officer/officer.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "laft", fichero: "laft/officer/officer.routes.ts", metodo: "POST", ruta: "/:id/revocar", roles: ["admin"], heredada: false },
  { modulo: "privacy", fichero: "privacy/privacy.routes.ts", metodo: "POST", ruta: "/forget", roles: ["admin"], heredada: false },
  { modulo: "privacy", fichero: "privacy/privacy.routes.ts", metodo: "GET", ruta: "/preview/:docNumber", roles: ["admin","compliance"], heredada: true },
  { modulo: "privacy", fichero: "privacy/pii-access.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","compliance"], heredada: true },
  { modulo: "privacy", fichero: "privacy/pii-access.routes.ts", metodo: "GET", ruta: "/stats", roles: ["admin","compliance"], heredada: true },
  { modulo: "firma", fichero: "firma/firma.routes.ts", metodo: "POST", ruta: "/:id/firma/solicitar", roles: ["admin"], heredada: false },
  { modulo: "firma", fichero: "firma/firma.routes.ts", metodo: "GET", ruta: "/:id/firma", roles: ["admin","transito"], heredada: false },
  { modulo: "drive", fichero: "drive/drive.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "drive", fichero: "drive/drive.routes.ts", metodo: "GET", ruta: "/search", roles: ["admin"], heredada: true },
  { modulo: "drive", fichero: "drive/drive.routes.ts", metodo: "GET", ruta: "/download/:fileId", roles: ["admin"], heredada: true },
  { modulo: "drive", fichero: "drive/drive.routes.ts", metodo: "GET", ruta: "/preview/:fileId", roles: ["admin"], heredada: true },
  { modulo: "drive", fichero: "drive/procesador.routes.ts", metodo: "POST", ruta: "/procesar-cuentas", roles: ["admin"], heredada: true },
  { modulo: "drive", fichero: "drive/procesador.routes.ts", metodo: "GET", ruta: "/cuentas-archivo/:dir/:filename", roles: ["admin"], heredada: true },
  { modulo: "soat", fichero: "soat/batch.routes.ts", metodo: "POST", ruta: "/batch-validate", roles: ["admin"], heredada: true },
  { modulo: "soat", fichero: "soat/batch.routes.ts", metodo: "POST", ruta: "/export-provider", roles: ["admin"], heredada: true },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "PATCH", ruta: "/:id/purchase", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "PATCH", ruta: "/:id/refresh-runt", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "PATCH", ruta: "/:id/verify", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "PATCH", ruta: "/:id/reject", roles: ["admin","proveedor"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "POST", ruta: "/upload-purchases", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "GET", ruta: "/export", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "GET", ruta: "/stats", roles: ["admin"], heredada: false },
  { modulo: "soat", fichero: "soat/soat.routes.ts", metodo: "POST", ruta: "/verificar-runt", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/credenciales.routes.ts", metodo: "GET", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "siigo", fichero: "siigo/credenciales.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: true },
  { modulo: "siigo", fichero: "siigo/credenciales.routes.ts", metodo: "POST", ruta: "/probar-conexion", roles: ["admin"], heredada: true },
  { modulo: "siigo", fichero: "siigo/credenciales.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: true },
  { modulo: "siigo", fichero: "siigo/compuerta.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades-mapeo.routes.ts", metodo: "GET", ruta: "/estado", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades-mapeo.routes.ts", metodo: "GET", ruta: "/propuestas", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades-mapeo.routes.ts", metodo: "GET", ruta: "/obsoletas", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades-mapeo.routes.ts", metodo: "GET", ruta: "/:id/propuesta", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades-mapeo.routes.ts", metodo: "POST", ruta: "/:id/confirmar", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "GET", ruta: "/paises", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "GET", ruta: "/buscar", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "GET", ruta: "/:pais/departamentos", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "GET", ruta: "/:pais/:departamento/ciudades", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/ciudades.routes.ts", metodo: "POST", ruta: "/cargar", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "GET", ruta: "/estado", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "POST", ruta: "/revalidar", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "POST", ruta: "/", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "POST", ruta: "/:id/producto", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "GET", ruta: "/:id", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "PATCH", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "POST", ruta: "/:id/confirmar", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/mapeo-conceptos.routes.ts", metodo: "DELETE", ruta: "/:id", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/linea-tiempo.routes.ts", metodo: "GET", ruta: "/:tramiteId", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/freno.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/freno.routes.ts", metodo: "POST", ruta: "/reactivar", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/parametrizacion.routes.ts", metodo: "GET", ruta: "/catalogos", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/parametrizacion.routes.ts", metodo: "GET", ruta: "/catalogos/:tipo", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/parametrizacion.routes.ts", metodo: "POST", ruta: "/catalogos/sincronizar", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/validador-cliente.routes.ts", metodo: "GET", ruta: "/validacion", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/validador-cliente.routes.ts", metodo: "GET", ruta: "/validacion/detalle", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/validador-cliente.routes.ts", metodo: "GET", ruta: "/:id/validacion", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/validador-cliente.routes.ts", metodo: "POST", ruta: "/validacion/recalcular-duplicados", roles: ["admin"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "GET", ruta: "*", condicion: "consultar", roles: ["admin","auditor","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "emitir", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "reintentar", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "reenviar_correo", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "marcar_fallido", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "reactivar", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "corregir", roles: ["admin","financiera"], heredada: false },
  { modulo: "siigo", fichero: "siigo/siigo.permisos.ts", metodo: "POST", ruta: "*", condicion: "anular", roles: ["admin","financiera"], heredada: false },
  { modulo: "runt", fichero: "runt/runt.routes.ts", metodo: "POST", ruta: "/consulta-persona", roles: ["admin"], heredada: false },
  { modulo: "runt", fichero: "runt/runt.routes.ts", metodo: "POST", ruta: "/ocr-cedula", roles: ["admin"], heredada: false },
  { modulo: "integraciones", fichero: "integraciones/integraciones.routes.ts", metodo: "GET", ruta: "/fasecolda/buscar", roles: ["admin"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/", roles: ["admin","auditor","lider_pesv","proveedor","supervisor_flota"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/:vin/historial", roles: ["admin","auditor","lider_pesv","proveedor","supervisor_flota"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "POST", ruta: "/:vin/historial/sync", roles: ["admin","auditor","lider_pesv","proveedor","supervisor_flota"], heredada: false },
  { modulo: "vehicles", fichero: "vehicles/vehicles.routes.ts", metodo: "GET", ruta: "/:vin/certificado", roles: ["admin","auditor","lider_pesv","proveedor","supervisor_flota"], heredada: false },
];
