-- 0179_permisos_modelo.sql
-- Feature #12072 — Roles y permisos configurables. HU #12081 (eslabon 1 de 1 → 2 → 3): el catalogo
--   de FUNCIONES y el reparto rol x funcion dejan de vivir dentro del programa y pasan a ser datos.
-- Autor: equipo FLITO. Antecedentes: ADR-0005 (eleccion de las clausulas ON DELETE), ADR-0015
--   (§Decision 4: los dos atajos de `admin` se retiran cuando ESTA migracion siembre sus marcas),
--   migracion 0178 (HU #12169, `permisos_roles` y `users.role` varchar con FK) y el Feature #12074
--   (migracion 0176, que retiro los estados de revision del canal Cliente — ver el AC3).
--
-- Depende de la 0178: las dos claves foraneas de `permisos_rol_funcion` no existen sin ella. El
-- orden relativo 0178 → 0179 → 0180 no es negociable.
--
-- Reglas de este archivo:
--   · Sin BEGIN/COMMIT propios (ADR-DB-001): el runner (`src/scripts/db-apply.ts`) envuelve cada
--     archivo y rechaza con exit 2 cualquier migracion >= 0071 que traiga control de transaccion.
--     El unico bloque DO va con dollar-quoting ETIQUETADO, y su etiqueta NO se cita con sus dolares
--     en ningun comentario: el escaner corre ANTES de quitar comentarios y emparejaria mal. Le costo
--     un exit 2 a la 0178.
--   · Idempotente en sentido fuerte (AC1): la segunda pasada no cambia ni una fila. De ahi el
--     `IF NOT EXISTS` de las tablas y el `ON CONFLICT DO NOTHING` de las tres siembras. NO se usa
--     `DO UPDATE` en ninguna: moveria filas en la segunda pasada y romperia el AC1.
--   · El SEED NO SE TECLEA (AC4). Sale de `npm run permisos:seed -w apps/api`, que lo construye
--     leyendo PAGES/PAGE_GROUPS/ROLE_DEFAULT_PAGES y las guardas `requireRole` del propio codigo
--     (apps/api/src/modules/permisos/). Volver a correrlo reproduce byte por byte el bloque de abajo;
--     si diverge, es que el codigo y el seed se separaron.

-- ── Paso 1 — El catalogo de funciones (AC1) ─────────────────────────────────────────────────────
-- `codigo` es PK textual e inmutable, igual que en `permisos_roles`: es el literal que la #12082 va
-- a comparar en cada guarda. Lo editable es `nombre_negocio`.
-- `activo` permite retirar una funcion sin borrarla — borrarla la impide el RESTRICT del paso 2 en
-- cuanto alguien la tenga concedida, y eso es deliberado.
CREATE TABLE IF NOT EXISTS permisos_funciones (
  codigo         varchar(80)  PRIMARY KEY,
  modulo         varchar(40)  NOT NULL,
  nombre_negocio varchar(120) NOT NULL,
  descripcion    text         NOT NULL,
  tipo           varchar(10)  NOT NULL,
  activo         boolean      NOT NULL DEFAULT true,
  CONSTRAINT permisos_funciones_tipo_chk CHECK (tipo IN ('pagina','operacion'))
);

CREATE INDEX IF NOT EXISTS idx_permisos_funciones_modulo ON permisos_funciones(modulo);

COMMENT ON TABLE permisos_funciones IS
  'Catalogo de funciones del producto (HU #12081). Lo declara el PRODUCTO y lo siembra esta '
  'migracion (CF-23): el administrador reparte funciones, no las inventa. Se genera desde el codigo '
  'con npm run permisos:seed -w apps/api.';
COMMENT ON COLUMN permisos_funciones.codigo IS
  'pagina.<slug> para las pantallas, <modulo>.<objeto>.<accion> para las operaciones. Inmutable.';
COMMENT ON COLUMN permisos_funciones.modulo IS
  'Agrupador de pantalla: el grupo de PAGE_GROUPS en las paginas, el modulo FLITO en las operaciones.';
COMMENT ON COLUMN permisos_funciones.tipo IS
  'pagina | operacion. Las 43 de tipo pagina son los 44 slugs de PAGES MENOS flito_ayuda, cuya '
  'visibilidad es derivada y no se concede a mano (AC2-bis).';

-- ── Paso 2 — Lo que concede un ROL (AC1) ────────────────────────────────────────────────────────
-- Las dos clausulas ON DELETE son asimetricas a proposito (ADR-0005): CASCADE hacia el rol —borrar
-- un rol se lleva su reparto, que sin el no significa nada— y RESTRICT hacia la funcion —una funcion
-- concedida no se borra por accidente; primero se retira de quien la tenga—.
-- ON UPDATE RESTRICT en las dos: los dos codigos son inmutables y que lo diga la definicion vale mas
-- que un comentario.
CREATE TABLE IF NOT EXISTS permisos_rol_funcion (
  rol_codigo     varchar(40) NOT NULL REFERENCES permisos_roles(codigo)
                   ON UPDATE RESTRICT ON DELETE CASCADE,
  funcion_codigo varchar(80) NOT NULL REFERENCES permisos_funciones(codigo)
                   ON UPDATE RESTRICT ON DELETE RESTRICT,
  PRIMARY KEY (rol_codigo, funcion_codigo)
);

-- La PK ya indexa por rol_codigo; este indice es el otro sentido, el que la pantalla de la #12084
-- necesita para «quien tiene esta funcion» y el que pide el RESTRICT al borrar una funcion.
CREATE INDEX IF NOT EXISTS idx_permisos_rol_funcion_funcion ON permisos_rol_funcion(funcion_codigo);

COMMENT ON TABLE permisos_rol_funcion IS
  'Reparto rol x funcion (HU #12081). El backfill de esta migracion reproduce exactamente el estado '
  'de hoy (CF-16): ROLE_DEFAULT_PAGES para las paginas y las guardas requireRole para las operaciones.';

-- ── Paso 3 — La excepcion por USUARIO (AC1) ─────────────────────────────────────────────────────
-- `efecto` nace con los dos valores aunque esta HU solo siembre 'conceder' (AC4): partir el modelo
-- en dos migraciones obligaria a reescribir la PK mas adelante. Quien escribe 'revocar' es la HU de
-- permisos por usuario, y hasta entonces la tabla no debe tener ni una fila con ese efecto.
CREATE TABLE IF NOT EXISTS permisos_usuario_funcion (
  user_id        integer     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  funcion_codigo varchar(80) NOT NULL REFERENCES permisos_funciones(codigo)
                   ON UPDATE RESTRICT ON DELETE RESTRICT,
  efecto         varchar(8)  NOT NULL,
  PRIMARY KEY (user_id, funcion_codigo),
  CONSTRAINT permisos_usuario_funcion_efecto_chk CHECK (efecto IN ('conceder','revocar'))
);

COMMENT ON TABLE permisos_usuario_funcion IS
  'Excepcion por usuario sobre lo que le da su rol (HU #12081). Esta migracion solo siembra '
  'conceder, desde users.allowed_pages; revocar llega con la HU de permisos por usuario.';

-- ── Paso 4 — SEED GENERADO (AC2, AC4) ───────────────────────────────────────────────────────────
-- Todo lo que va desde aqui hasta la marca de cierre es la salida literal de
--   npm run --silent permisos:seed -w apps/api
-- No se edita a mano: se regenera. Si una guarda `requireRole` cambia en el codigo, lo que cambia
-- aqui es el reparto, y el que lo cambia es el generador.
--
-- Lo que NO esta, y esta medido (AC3): ninguna funcion de validar, rechazar con causal, ver causales
-- ni subsanar en el canal Cliente. El Feature #12074 retiro esas rutas en la migracion 0176, asi que
-- el lector de guardas no las encuentra y el catalogo no las declara. Un test las fija por codigo
-- para que reponerlas obligue a reabrir la decision.
-- 260 funciones: 43 de tipo 'pagina' y 217 de tipo 'operacion'.
-- 484 filas de reparto. Regenerar con: npm run permisos:seed -w apps/api

-- Catálogo de funciones (AC2). Generado: no editar a mano.
INSERT INTO permisos_funciones (codigo, modulo, nombre_negocio, descripcion, tipo) VALUES
  ('bitacora.bitacora.ver', 'bitacora', 'Ver la bitácora', 'Consultar el registro de quién cambió qué y cuándo.', 'operacion'),
  ('bitacora.bitacora.ver_recurso', 'bitacora', 'Ver la bitácora de un registro', 'Consultar el historial de auditoría de un registro concreto.', 'operacion'),
  ('bolsas.alertas.ver', 'bolsas', 'Ver las alertas de bolsas', 'Consultar los avisos de saldo bajo y de movimientos atípicos.', 'operacion'),
  ('bolsas.bolsa.ver', 'bolsas', 'Ver la bolsa de una compañía', 'Consultar el saldo y el estado de la bolsa de un cliente.', 'operacion'),
  ('bolsas.cierre.crear', 'bolsas', 'Cerrar un periodo de bolsa', 'Cuadrar y cerrar el periodo de la bolsa del cliente.', 'operacion'),
  ('bolsas.cierres.ver', 'bolsas', 'Ver los cierres de una bolsa', 'Consultar los cortes de periodo ya cerrados.', 'operacion'),
  ('bolsas.consolidado.ver', 'bolsas', 'Ver el consolidado de bolsas', 'Consultar el saldo agregado de todas las bolsas prepago.', 'operacion'),
  ('bolsas.extracto.descargar', 'bolsas', 'Descargar el extracto de una bolsa', 'Bajar el estado de cuenta de la bolsa del cliente.', 'operacion'),
  ('bolsas.movimiento.corregir', 'bolsas', 'Corregir un movimiento de bolsa', 'Rectificar un movimiento ya registrado dejando el rastro.', 'operacion'),
  ('bolsas.movimiento.registrar', 'bolsas', 'Registrar un movimiento manual', 'Cargar a mano una entrada o salida que no vino de un trámite.', 'operacion'),
  ('bolsas.movimientos.ver', 'bolsas', 'Ver los movimientos de una bolsa', 'Recorrer las entradas y salidas de dinero de la bolsa.', 'operacion'),
  ('bolsas.recarga.registrar', 'bolsas', 'Registrar una recarga de bolsa', 'Abonar dinero a la bolsa del cliente con su soporte.', 'operacion'),
  ('bolsas.riesgo.ver', 'bolsas', 'Ver el riesgo de saldo', 'Consultar qué bolsas están cerca de quedarse sin fondos.', 'operacion'),
  ('bolsas.soporte.descargar', 'bolsas', 'Descargar el soporte de un movimiento', 'Abrir el comprobante que respalda un movimiento de bolsa.', 'operacion'),
  ('bolsas.transito.cargar', 'bolsas', 'Cargar saldo a una bolsa de organismo', 'Abonar dinero a la bolsa de derechos con su soporte.', 'operacion'),
  ('bolsas.transito.crear', 'bolsas', 'Crear una bolsa de organismo', 'Abrir una bolsa de derechos ante un organismo de tránsito.', 'operacion'),
  ('bolsas.transito.editar', 'bolsas', 'Editar una bolsa de organismo', 'Cambiar los datos de la bolsa de derechos.', 'operacion'),
  ('bolsas.transito.listar', 'bolsas', 'Ver las bolsas de organismos', 'Listar las bolsas de derechos abiertas ante los organismos de tránsito.', 'operacion'),
  ('bolsas.transito.ver', 'bolsas', 'Ver una bolsa de organismo', 'Consultar el saldo y el detalle de una bolsa de derechos.', 'operacion'),
  ('bolsas.transito.ver_movimientos', 'bolsas', 'Ver los movimientos de una bolsa de organismo', 'Recorrer las cargas y consumos de la bolsa de derechos.', 'operacion'),
  ('comparendos.causales.crear', 'comparendos', 'Añadir una causal de comparendo', 'Registrar una infracción nueva en el catálogo.', 'operacion'),
  ('comparendos.causales.editar', 'comparendos', 'Editar una causal de comparendo', 'Corregir la descripción o el estado de una infracción.', 'operacion'),
  ('comparendos.causales.listar', 'comparendos', 'Ver las causales de comparendo', 'Consultar el catálogo de infracciones y su descripción.', 'operacion'),
  ('comparendos.municipios.crear', 'comparendos', 'Añadir un municipio', 'Configurar una fuente municipal nueva de comparendos.', 'operacion'),
  ('comparendos.municipios.editar', 'comparendos', 'Editar un municipio', 'Cambiar la configuración o el estado de una fuente municipal.', 'operacion'),
  ('comparendos.municipios.listar', 'comparendos', 'Ver los municipios consultados', 'Listar las fuentes municipales de comparendos configuradas.', 'operacion'),
  ('comparendos.nits.borrar', 'comparendos', 'Quitar un NIT vigilado', 'Sacar una compañía del monitoreo de comparendos.', 'operacion'),
  ('comparendos.nits.crear', 'comparendos', 'Añadir un NIT vigilado', 'Poner una compañía bajo monitoreo de comparendos.', 'operacion'),
  ('comparendos.nits.editar', 'comparendos', 'Editar un NIT vigilado', 'Cambiar los datos o el estado de un NIT monitoreado.', 'operacion'),
  ('comparendos.nits.listar', 'comparendos', 'Ver los NIT vigilados', 'Listar las compañías a las que se les monitorean comparendos.', 'operacion'),
  ('comparendos.registro.gestionar', 'comparendos', 'Gestionar un comparendo', 'Anotar el estado de gestión y las observaciones del comparendo.', 'operacion'),
  ('comparendos.registro.ver', 'comparendos', 'Ver un comparendo', 'Abrir el detalle de un comparendo concreto.', 'operacion'),
  ('comparendos.registro.ver_eventos', 'comparendos', 'Ver los eventos de un comparendo', 'Consultar cómo ha cambiado el comparendo entre consultas.', 'operacion'),
  ('comparendos.registros.buscar', 'comparendos', 'Buscar comparendos', 'Filtrar los comparendos por placa, NIT o documento.', 'operacion'),
  ('comparendos.registros.exportar', 'comparendos', 'Exportar comparendos', 'Descargar el listado filtrado de comparendos.', 'operacion'),
  ('comparendos.registros.listar', 'comparendos', 'Ver los comparendos', 'Recorrer los comparendos detectados en los NIT vigilados.', 'operacion'),
  ('comparendos.simit.guardar_token', 'comparendos', 'Guardar el acceso al SIMIT', 'Registrar la credencial con la que se consulta el SIMIT.', 'operacion'),
  ('comparendos.simit.ver_token', 'comparendos', 'Ver el estado del acceso al SIMIT', 'Comprobar si hay credencial vigente para consultar el SIMIT.', 'operacion'),
  ('comparendos.sync.lanzar', 'comparendos', 'Lanzar la consulta de comparendos', 'Disparar a mano la sincronización contra SIMIT y municipios.', 'operacion'),
  ('comparendos.sync.ver_corrida', 'comparendos', 'Ver una corrida de sincronización', 'Abrir el detalle paso a paso de una consulta.', 'operacion'),
  ('comparendos.sync.ver_corridas', 'comparendos', 'Ver las corridas de sincronización', 'Listar las consultas hechas y cómo terminaron.', 'operacion'),
  ('compuerta.cola.ver', 'compuerta', 'Ver la compuerta de entrega', 'Abrir el listado de trámites listos para entregar.', 'operacion'),
  ('compuerta.tramite.entregar', 'compuerta', 'Entregar un trámite', 'Dar por entregado el trámite al cliente y cerrar la compuerta.', 'operacion'),
  ('compuerta.tramite.ver', 'compuerta', 'Ver un trámite en la compuerta', 'Consultar qué le falta a un trámite para poder entregarse.', 'operacion'),
  ('conciliacion.boleta.cargar', 'conciliacion', 'Cargar una boleta de recaudo', 'Subir el archivo del portal con lo recaudado en el periodo.', 'operacion'),
  ('conciliacion.boleta.conciliar', 'conciliacion', 'Conciliar una boleta', 'Dar por cuadrada la boleta y cerrarla.', 'operacion'),
  ('conciliacion.boleta.descartar', 'conciliacion', 'Descartar una boleta', 'Anular una boleta cargada por error.', 'operacion'),
  ('conciliacion.boleta.recruzar', 'conciliacion', 'Volver a cruzar una boleta', 'Repetir el cruce de la boleta tras corregir los datos.', 'operacion'),
  ('conciliacion.boleta.ver', 'conciliacion', 'Ver una boleta de recaudo', 'Abrir el cruce de una boleta contra lo emitido.', 'operacion'),
  ('conciliacion.boletas.listar', 'conciliacion', 'Ver las boletas de recaudo', 'Listar las boletas cargadas y su estado de conciliación.', 'operacion'),
  ('conciliacion.comprobante.cargar', 'conciliacion', 'Cargar el comprobante de una boleta', 'Adjuntar el soporte de la consignación del recaudo.', 'operacion'),
  ('conciliacion.comprobante.descargar', 'conciliacion', 'Descargar el comprobante de una boleta', 'Abrir el soporte de la consignación del recaudo.', 'operacion'),
  ('conciliacion.comprobante.reemplazar', 'conciliacion', 'Reemplazar el comprobante de una boleta', 'Sustituir el soporte de consignación por otro.', 'operacion'),
  ('derechos.candidatos.ver', 'derechos', 'Ver los trámites candidatos de una placa', 'Consultar a qué trámites podría corresponder un recibo por su placa.', 'operacion'),
  ('derechos.cola.filtrar', 'derechos', 'Filtrar los derechos de tránsito', 'Leer los contadores y las facetas del listado de derechos.', 'operacion'),
  ('derechos.cola.ver', 'derechos', 'Ver los derechos de tránsito', 'Abrir el listado de recibos de derechos cobrados por el organismo.', 'operacion'),
  ('derechos.drive.listar', 'derechos', 'Ver los archivos de derechos en Drive', 'Listar los recibos que esperan proceso en la carpeta de Drive.', 'operacion'),
  ('derechos.drive.procesar', 'derechos', 'Procesar los recibos de Drive', 'Lanzar la lectura de los recibos pendientes en la carpeta de Drive.', 'operacion'),
  ('derechos.drive.ver_registro', 'derechos', 'Ver el registro de proceso de Drive', 'Consultar qué archivos de Drive se procesaron y con qué resultado.', 'operacion'),
  ('derechos.recibos.cargar', 'derechos', 'Cargar recibos de derechos de tránsito', 'Subir los archivos de recibos para que el sistema los lea y los cruce.', 'operacion'),
  ('derechos.soporte.descargar', 'derechos', 'Descargar el soporte de un derecho', 'Abrir el archivo del recibo de derechos.', 'operacion'),
  ('impuestos.certificado.descargar', 'impuestos', 'Descargar el certificado de impuestos', 'Bajar el documento que acredita el pago del impuesto.', 'operacion'),
  ('impuestos.cola.filtrar', 'impuestos', 'Filtrar la cola de impuestos', 'Leer los contadores y las facetas con las que se acota la bandeja.', 'operacion'),
  ('impuestos.cola.ver', 'impuestos', 'Ver la cola de impuestos', 'Abrir la bandeja de trámites de impuesto vehicular.', 'operacion'),
  ('impuestos.excel.exportar', 'impuestos', 'Exportar la cola de impuestos a Excel', 'Descargar el listado filtrado como archivo de Excel.', 'operacion'),
  ('impuestos.factura.ver', 'impuestos', 'Ver la factura de venta del trámite de impuestos', 'Abrir la factura de venta asociada al trámite.', 'operacion'),
  ('impuestos.recibos.cargar', 'impuestos', 'Cargar recibos de impuestos', 'Subir los recibos de pago y repartirlos por trámite.', 'operacion'),
  ('impuestos.soportes.descargar', 'impuestos', 'Descargar soportes de impuestos en ZIP', 'Bajar en un solo archivo los soportes de los trámites seleccionados.', 'operacion'),
  ('impuestos.tramite.certificar', 'impuestos', 'Certificar un trámite de impuestos', 'Dar por pagado y certificado el impuesto de un vehículo.', 'operacion'),
  ('impuestos.tramite.certificar_lote', 'impuestos', 'Certificar trámites de impuestos en lote', 'Certificar de una vez todos los trámites seleccionados.', 'operacion'),
  ('impuestos.tramite.enviar', 'impuestos', 'Enviar trámites de impuestos al gestor', 'Pasar trámites al gestor de impuestos del organismo.', 'operacion'),
  ('impuestos.tramite.reactivar', 'impuestos', 'Reactivar un trámite de impuestos', 'Volver a poner en curso un trámite rechazado o detenido.', 'operacion'),
  ('impuestos.tramite.rechazar', 'impuestos', 'Rechazar un trámite de impuestos', 'Devolver el trámite al origen indicando por qué no procede.', 'operacion'),
  ('impuestos.tramite.reversar', 'impuestos', 'Reversar un trámite de impuestos', 'Deshacer el último avance de estado del trámite.', 'operacion'),
  ('impuestos.tramite.ver', 'impuestos', 'Ver un trámite de impuestos', 'Abrir el detalle de un trámite concreto.', 'operacion'),
  ('impuestos.tramite.ver_historial', 'impuestos', 'Ver el historial de un trámite de impuestos', 'Consultar la línea de tiempo de cambios de estado del trámite.', 'operacion'),
  ('impuestos.tramite.ver_soportes', 'impuestos', 'Ver los soportes de un trámite de impuestos', 'Listar y abrir los documentos adjuntos del trámite.', 'operacion'),
  ('liquidacion.liquidacion.facturar', 'liquidacion', 'Facturar un trámite liquidado', 'Emitir la factura del trámite ya liquidado.', 'operacion'),
  ('liquidacion.liquidacion.liquidar', 'liquidacion', 'Liquidar un trámite', 'Calcular y fijar lo que se le cobra al cliente por el trámite.', 'operacion'),
  ('liquidacion.liquidacion.liquidar_lote', 'liquidacion', 'Liquidar trámites en lote', 'Liquidar de una vez todos los trámites seleccionados.', 'operacion'),
  ('liquidacion.liquidacion.reversar', 'liquidacion', 'Reversar una liquidación', 'Deshacer la liquidación de un trámite.', 'operacion'),
  ('liquidacion.liquidacion.ver', 'liquidacion', 'Ver la liquidación de un trámite', 'Consultar los valores liquidados al trámite.', 'operacion'),
  ('liquidacion.liquidacion.ver_eventos', 'liquidacion', 'Ver los eventos de una liquidación', 'Consultar el historial de liquidación del trámite.', 'operacion'),
  ('logistica.actas.descargar', 'logistica', 'Descargar el PDF de un acta', 'Bajar el acta firmada en formato PDF.', 'operacion'),
  ('logistica.actas.despachar', 'logistica', 'Despachar un acta', 'Poner en ruta el acta y sus documentos.', 'operacion'),
  ('logistica.actas.devolver', 'logistica', 'Devolver un acta', 'Registrar que el acta vuelve sin haberse entregado.', 'operacion'),
  ('logistica.actas.entregar', 'logistica', 'Entregar un acta', 'Registrar la entrega del acta en destino.', 'operacion'),
  ('logistica.actas.listar', 'logistica', 'Ver las actas de logística', 'Listar las actas de despacho y entrega.', 'operacion'),
  ('logistica.actas.ver', 'logistica', 'Ver un acta de logística', 'Abrir el detalle de un acta y sus documentos.', 'operacion'),
  ('logistica.consola.filtrar', 'logistica', 'Filtrar la consola de logística', 'Leer los contadores y las facetas de la consola.', 'operacion'),
  ('logistica.consola.ver', 'logistica', 'Ver la consola de logística', 'Abrir la trazabilidad de documentos en tránsito.', 'operacion'),
  ('logistica.documento.escanear', 'logistica', 'Escanear un documento en campo', 'Registrar el paso de un documento leyendo su código de barras.', 'operacion'),
  ('logistica.documento.reportar_novedad', 'logistica', 'Reportar una novedad de entrega', 'Dejar constancia de que la entrega no se pudo completar y por qué.', 'operacion'),
  ('logistica.documento.reversar', 'logistica', 'Reversar un paso de logística', 'Deshacer el último movimiento registrado sobre el documento.', 'operacion'),
  ('logistica.documento.ver', 'logistica', 'Ver un documento en logística', 'Consultar el detalle y el recorrido de un documento.', 'operacion'),
  ('logistica.lote.cerrar', 'logistica', 'Cerrar un lote de logística', 'Dar por armado el lote de documentos que va a despacharse.', 'operacion'),
  ('logistica.lt.validar', 'logistica', 'Validar un número de guía', 'Comprobar que la guía de transporte existe y corresponde.', 'operacion'),
  ('logistica.ruta.ver', 'logistica', 'Ver mi ruta de mensajería', 'Consultar las recogidas y entregas asignadas al mensajero.', 'operacion'),
  ('pagina.clients', 'flito_soat_e_impuestos', 'Clientes y proveedores', 'Entrar a la pantalla «Clientes y proveedores».', 'pagina'),
  ('pagina.dashboard', 'general', 'Tablero de control', 'Entrar a la pantalla «Tablero de control».', 'pagina'),
  ('pagina.drive', 'operaciones', 'Google Drive', 'Entrar a la pantalla «Google Drive».', 'pagina'),
  ('pagina.finanzas_reporte_costos', 'finanzas', 'Finanzas — Reporte de costos', 'Entrar a la pantalla «Finanzas — Reporte de costos».', 'pagina'),
  ('pagina.fleet', 'flota', 'Flota', 'Entrar a la pantalla «Flota».', 'pagina'),
  ('pagina.flito_bitacora', 'flito_soat_e_impuestos', 'FLITO — Bitácora', 'Entrar a la pantalla «FLITO — Bitácora».', 'pagina'),
  ('pagina.flito_bolsas', 'flito_soat_e_impuestos', 'FLITO — Bolsas prepago', 'Entrar a la pantalla «FLITO — Bolsas prepago».', 'pagina'),
  ('pagina.flito_comparendos', 'flito_soat_e_impuestos', 'FLITO — Comparendos', 'Entrar a la pantalla «FLITO — Comparendos».', 'pagina'),
  ('pagina.flito_compuerta', 'flito_soat_e_impuestos', 'FLITO — Compuerta de entrega', 'Entrar a la pantalla «FLITO — Compuerta de entrega».', 'pagina'),
  ('pagina.flito_conciliacion', 'flito_soat_e_impuestos', 'FLITO — Conciliación', 'Entrar a la pantalla «FLITO — Conciliación».', 'pagina'),
  ('pagina.flito_derechos', 'flito_soat_e_impuestos', 'FLITO — Derechos de tránsito', 'Entrar a la pantalla «FLITO — Derechos de tránsito».', 'pagina'),
  ('pagina.flito_impuestos', 'flito_soat_e_impuestos', 'FLITO — Impuestos', 'Entrar a la pantalla «FLITO — Impuestos».', 'pagina'),
  ('pagina.flito_logistica', 'flito_soat_e_impuestos', 'FLITO — Logística', 'Entrar a la pantalla «FLITO — Logística».', 'pagina'),
  ('pagina.flito_logistica_ruta', 'flito_soat_e_impuestos', 'FLITO — Mi ruta (mensajero)', 'Entrar a la pantalla «FLITO — Mi ruta (mensajero)».', 'pagina'),
  ('pagina.flito_revisiones', 'flito_soat_e_impuestos', 'FLITO — Revisión OCR', 'Entrar a la pantalla «FLITO — Revisión OCR».', 'pagina'),
  ('pagina.flito_soat', 'flito_soat_e_impuestos', 'FLITO — SOAT', 'Entrar a la pantalla «FLITO — SOAT».', 'pagina'),
  ('pagina.flito_tablero', 'flito_soat_e_impuestos', 'FLITO — Tablero', 'Entrar a la pantalla «FLITO — Tablero».', 'pagina'),
  ('pagina.flito_tramites', 'flito_soat_e_impuestos', 'FLITO — Trámites', 'Entrar a la pantalla «FLITO — Trámites».', 'pagina'),
  ('pagina.laft', 'cumplimiento_laft', 'Cumplimiento LAFT', 'Entrar a la pantalla «Cumplimiento LAFT».', 'pagina'),
  ('pagina.laft_audit_plan', 'cumplimiento_laft', 'LAFT — Plan de auditorías', 'Entrar a la pantalla «LAFT — Plan de auditorías».', 'pagina'),
  ('pagina.laft_dashboard', 'cumplimiento_laft', 'LAFT — Tablero', 'Entrar a la pantalla «LAFT — Tablero».', 'pagina'),
  ('pagina.laft_manual', 'cumplimiento_laft', 'LAFT — Manual SARLAFT', 'Entrar a la pantalla «LAFT — Manual SARLAFT».', 'pagina'),
  ('pagina.laft_oficial', 'cumplimiento_laft', 'LAFT — Oficial cumplimiento', 'Entrar a la pantalla «LAFT — Oficial cumplimiento».', 'pagina'),
  ('pagina.laft_trainings', 'cumplimiento_laft', 'Capacitaciones', 'Entrar a la pantalla «Capacitaciones».', 'pagina'),
  ('pagina.laft_unusual', 'cumplimiento_laft', 'Operaciones inusuales', 'Entrar a la pantalla «Operaciones inusuales».', 'pagina'),
  ('pagina.maintenance', 'mantenimiento', 'Mantenimiento', 'Entrar a la pantalla «Mantenimiento».', 'pagina'),
  ('pagina.pesv', 'pesv', 'PESV — Conductores', 'Entrar a la pantalla «PESV — Conductores».', 'pagina'),
  ('pagina.pesv_normativa', 'pesv', 'PESV — Tracker normativo', 'Entrar a la pantalla «PESV — Tracker normativo».', 'pagina'),
  ('pagina.pesv_raci', 'pesv', 'PESV — Matriz RACI', 'Entrar a la pantalla «PESV — Matriz RACI».', 'pagina'),
  ('pagina.pesv_retencion', 'pesv', 'PESV — Retención documental', 'Entrar a la pantalla «PESV — Retención documental».', 'pagina'),
  ('pagina.privacy', 'administracion', 'Privacidad y datos', 'Entrar a la pantalla «Privacidad y datos».', 'pagina'),
  ('pagina.rndc', 'rndc', 'RNDC y manifiestos', 'Entrar a la pantalla «RNDC y manifiestos».', 'pagina'),
  ('pagina.rndc_admin', 'rndc', 'Catálogos RNDC', 'Entrar a la pantalla «Catálogos RNDC».', 'pagina'),
  ('pagina.siigo_credenciales', 'administracion', 'Facturación electrónica — Credenciales', 'Entrar a la pantalla «Facturación electrónica — Credenciales».', 'pagina'),
  ('pagina.siigo_operacion', 'finanzas', 'Facturación electrónica — Operación', 'Entrar a la pantalla «Facturación electrónica — Operación».', 'pagina'),
  ('pagina.siigo_parametrizacion', 'finanzas', 'Facturación electrónica — Parametrización', 'Entrar a la pantalla «Facturación electrónica — Parametrización».', 'pagina'),
  ('pagina.soat', 'operaciones', 'SOAT', 'Entrar a la pantalla «SOAT».', 'pagina'),
  ('pagina.tax_reader', 'operaciones', 'Lectura de Impuestos', 'Entrar a la pantalla «Lectura de Impuestos».', 'pagina'),
  ('pagina.tramite', 'operaciones', 'Trámite Digital', 'Entrar a la pantalla «Trámite Digital».', 'pagina'),
  ('pagina.transito', 'operaciones', 'Tránsito', 'Entrar a la pantalla «Tránsito».', 'pagina'),
  ('pagina.transito_organismos', 'transito', 'Organismos de tránsito', 'Entrar a la pantalla «Organismos de tránsito».', 'pagina'),
  ('pagina.users', 'administracion', 'Usuarios', 'Entrar a la pantalla «Usuarios».', 'pagina'),
  ('pagina.vehicles', 'operaciones', 'Vehículos', 'Entrar a la pantalla «Vehículos».', 'pagina'),
  ('parametrizacion.companias.editar', 'parametrizacion', 'Editar una compañía cliente', 'Cambiar la configuración comercial y operativa de la compañía.', 'operacion'),
  ('parametrizacion.companias.listar', 'parametrizacion', 'Ver las compañías cliente', 'Consultar las compañías dadas de alta y su configuración.', 'operacion'),
  ('parametrizacion.organismos.editar', 'parametrizacion', 'Editar un organismo de tránsito', 'Cambiar la parametrización FLITO del organismo.', 'operacion'),
  ('parametrizacion.organismos.fijar_modalidad', 'parametrizacion', 'Fijar la modalidad de un organismo', 'Definir cómo se paga a ese organismo a partir de una fecha.', 'operacion'),
  ('parametrizacion.organismos.listar', 'parametrizacion', 'Ver los organismos de tránsito', 'Consultar los organismos y su parametrización FLITO.', 'operacion'),
  ('parametrizacion.organismos.ver_vigencias', 'parametrizacion', 'Ver las vigencias de un organismo', 'Consultar los periodos de tarifas y modalidades del organismo.', 'operacion'),
  ('parametrizacion.proveedores.crear', 'parametrizacion', 'Añadir un proveedor SOAT', 'Registrar un gestor SOAT nuevo.', 'operacion'),
  ('parametrizacion.proveedores.editar', 'parametrizacion', 'Editar un proveedor SOAT', 'Cambiar los datos o el estado de un gestor SOAT.', 'operacion'),
  ('parametrizacion.proveedores.listar', 'parametrizacion', 'Ver los proveedores SOAT', 'Consultar los gestores SOAT registrados.', 'operacion'),
  ('parametrizacion.tarifas.borrar', 'parametrizacion', 'Borrar una tarifa', 'Retirar una tarifa del cuadro de precios.', 'operacion'),
  ('parametrizacion.tarifas.crear', 'parametrizacion', 'Crear una tarifa', 'Fijar el precio de un concepto para una compañía.', 'operacion'),
  ('parametrizacion.tarifas.editar', 'parametrizacion', 'Editar una tarifa', 'Cambiar el precio o la vigencia de una tarifa.', 'operacion'),
  ('parametrizacion.tarifas.listar', 'parametrizacion', 'Ver las tarifas', 'Consultar lo que se le cobra a cada compañía por cada concepto.', 'operacion'),
  ('revisiones.campos.ver', 'revisiones', 'Ver los campos revisables de un módulo', 'Consultar qué campos entran a revisión en cada módulo.', 'operacion'),
  ('revisiones.cola.ver', 'revisiones', 'Ver la cola de revisión OCR', 'Abrir la bandeja de campos que el OCR dejó dudosos.', 'operacion'),
  ('revisiones.revision.descartar', 'revisiones', 'Descartar una revisión OCR', 'Cerrar la revisión sin cambiar el dato.', 'operacion'),
  ('revisiones.revision.resolver', 'revisiones', 'Resolver una revisión OCR', 'Confirmar o corregir el valor leído y darlo por bueno.', 'operacion'),
  ('revisiones.soporte.descargar', 'revisiones', 'Abrir el documento en revisión', 'Ver el archivo original del que salió el dato dudoso.', 'operacion'),
  ('soat.cola.filtrar', 'soat', 'Filtrar la cola de SOAT', 'Leer los contadores y las facetas con las que se acota la bandeja.', 'operacion'),
  ('soat.cola.ver', 'soat', 'Ver la cola de SOAT', 'Abrir la bandeja de solicitudes de SOAT y recorrer su listado.', 'operacion'),
  ('soat.comprobante.cargar', 'soat', 'Cargar el comprobante de un SOAT', 'Adjuntar a la solicitud la póliza o la factura de venta emitida.', 'operacion'),
  ('soat.excel.exportar', 'soat', 'Exportar la cola de SOAT a Excel', 'Descargar el listado filtrado como archivo de Excel.', 'operacion'),
  ('soat.factura.leer', 'soat', 'Leer la factura de venta del vehículo', 'Extraer del PDF de la factura los datos del vehículo para prellenar la solicitud.', 'operacion'),
  ('soat.masiva.cargar', 'soat', 'Cargar comprobantes de SOAT en lote', 'Subir varios comprobantes de una vez y repartirlos por solicitud.', 'operacion'),
  ('soat.proveedor.cambiar', 'soat', 'Cambiar el proveedor de una solicitud de SOAT', 'Reasignar la solicitud a otro gestor SOAT.', 'operacion'),
  ('soat.runt.preconsultar', 'soat', 'Preconsultar un vehículo en el RUNT', 'Verificar en el RUNT los datos del vehículo antes de radicar.', 'operacion'),
  ('soat.solicitud.asumir', 'soat', 'Asumir una solicitud de SOAT en Operaciones', 'Sacar la solicitud del gestor y trabajarla desde Operaciones.', 'operacion'),
  ('soat.solicitud.crear', 'soat', 'Radicar una solicitud de SOAT', 'Crear una solicitud de SOAT desde el canal del cliente.', 'operacion'),
  ('soat.solicitud.devolver', 'soat', 'Devolver una solicitud de SOAT al gestor', 'Regresar al proveedor una solicitud que Operaciones había asumido.', 'operacion'),
  ('soat.solicitud.enviar', 'soat', 'Enviar solicitudes de SOAT al gestor', 'Pasar solicitudes al proveedor para que las expida.', 'operacion'),
  ('soat.solicitud.reactivar', 'soat', 'Reactivar una solicitud de SOAT', 'Volver a poner en curso una solicitud rechazada o detenida.', 'operacion'),
  ('soat.solicitud.rechazar', 'soat', 'Rechazar una solicitud de SOAT', 'Devolver la solicitud al origen indicando por qué no procede.', 'operacion'),
  ('soat.solicitud.reversar', 'soat', 'Reversar una solicitud de SOAT', 'Deshacer el último avance de estado de la solicitud.', 'operacion'),
  ('soat.solicitud.ver', 'soat', 'Ver una solicitud de SOAT', 'Abrir el detalle de una solicitud concreta.', 'operacion'),
  ('soat.solicitud.ver_historial', 'soat', 'Ver el historial de una solicitud de SOAT', 'Consultar la línea de tiempo de cambios de estado de la solicitud.', 'operacion'),
  ('soat.solicitud.ver_soportes', 'soat', 'Ver los soportes de una solicitud de SOAT', 'Listar y abrir los documentos adjuntos de la solicitud.', 'operacion'),
  ('soat.soportes.descargar', 'soat', 'Descargar soportes de SOAT en ZIP', 'Bajar en un solo archivo los soportes de las solicitudes seleccionadas.', 'operacion'),
  ('sync.sync.lanzar', 'sync', 'Lanzar la sincronización', 'Disparar a mano la sincronización de datos FLITO.', 'operacion'),
  ('sync.sync.ver_estado', 'sync', 'Ver el estado de la sincronización', 'Consultar cuándo corrió la última sincronización y cómo fue.', 'operacion'),
  ('tablero.tablero.ver', 'tablero', 'Ver el tablero FLITO', 'Consultar los indicadores consolidados de la operación.', 'operacion'),
  ('tramite.checklist.sugerir', 'tramite', 'Sugerir el checklist de un trámite', 'Proponer la lista de documentos a partir de la tipología.', 'operacion'),
  ('tramite.checklist.ver', 'tramite', 'Ver el checklist de un trámite', 'Consultar qué documentos exige el organismo para ese trámite.', 'operacion'),
  ('tramite.cola.ver', 'tramite', 'Ver la cola de Trámite Digital', 'Abrir la bandeja de trámites de tránsito.', 'operacion'),
  ('tramite.contrato.generar', 'tramite', 'Generar el contrato', 'Producir el contrato de compraventa del trámite.', 'operacion'),
  ('tramite.documentos.borrar', 'tramite', 'Borrar un documento del trámite', 'Retirar del trámite un documento adjunto.', 'operacion'),
  ('tramite.documentos.cargar', 'tramite', 'Cargar un documento del trámite', 'Adjuntar al trámite un documento del checklist.', 'operacion'),
  ('tramite.documentos.descargar', 'tramite', 'Descargar un documento del trámite', 'Abrir el archivo de un documento adjunto.', 'operacion'),
  ('tramite.documentos.listar', 'tramite', 'Ver los documentos de un trámite', 'Listar lo que se ha adjuntado al trámite.', 'operacion'),
  ('tramite.embudo.ver', 'tramite', 'Ver el embudo de trámites', 'Consultar cuántos trámites hay en cada etapa.', 'operacion'),
  ('tramite.estadisticas.ver_metricas', 'tramite', 'Ver las estadísticas de trámites', 'Consultar tiempos y volúmenes de la operación.', 'operacion'),
  ('tramite.estadisticas.ver_resumen', 'tramite', 'Ver el resumen de estadísticas', 'Consultar el consolidado de la operación de trámites.', 'operacion'),
  ('tramite.expediente.descargar', 'tramite', 'Descargar el expediente del trámite', 'Bajar en un PDF todo el trámite y sus documentos.', 'operacion'),
  ('tramite.fur.generar', 'tramite', 'Generar el FUR', 'Producir el Formulario Único de Registro del trámite.', 'operacion'),
  ('tramite.identidad.certificar', 'tramite', 'Emitir el certificado de validación', 'Producir el documento que acredita la validación de identidad.', 'operacion'),
  ('tramite.identidad.iniciar', 'tramite', 'Iniciar la validación de identidad', 'Enviar al titular el enlace para validar su identidad.', 'operacion'),
  ('tramite.identidad.iniciar_partes', 'tramite', 'Iniciar la validación de todas las partes', 'Enviar el enlace de validación a comprador y vendedor a la vez.', 'operacion'),
  ('tramite.identidad.seguir', 'tramite', 'Seguir la validación de identidad en vivo', 'Recibir en pantalla el avance de la validación mientras ocurre.', 'operacion'),
  ('tramite.identidad.ver_documentos', 'tramite', 'Ver los documentos de identidad', 'Abrir las cédulas y selfies aportadas en la validación.', 'operacion'),
  ('tramite.identidad.ver_estado', 'tramite', 'Ver el estado de la validación de identidad', 'Consultar quién ha validado ya y quién no.', 'operacion'),
  ('tramite.improntas.generar', 'tramite', 'Generar la hoja de improntas', 'Producir el documento de improntas del vehículo.', 'operacion'),
  ('tramite.impuesto.consultar', 'tramite', 'Consultar el impuesto vehicular', 'Preguntar al organismo cuánto debe el vehículo.', 'operacion'),
  ('tramite.lote.confirmar', 'tramite', 'Confirmar una carga masiva', 'Dar por buena la previsualización y crear los trámites.', 'operacion'),
  ('tramite.lote.crear', 'tramite', 'Crear una carga masiva', 'Radicar de una vez los trámites del archivo.', 'operacion'),
  ('tramite.lote.descargar_plantilla', 'tramite', 'Descargar la plantilla de carga masiva', 'Bajar el archivo modelo para radicar trámites en lote.', 'operacion'),
  ('tramite.lote.descargar_resultados', 'tramite', 'Descargar los resultados de una carga masiva', 'Bajar el archivo con el resultado fila a fila.', 'operacion'),
  ('tramite.lote.listar', 'tramite', 'Ver las cargas masivas', 'Listar los lotes de trámites radicados.', 'operacion'),
  ('tramite.lote.previsualizar', 'tramite', 'Previsualizar una carga masiva', 'Ver qué se va a crear antes de confirmar el lote.', 'operacion'),
  ('tramite.lote.procesar_async', 'tramite', 'Procesar una carga masiva en segundo plano', 'Lanzar el lote para que se procese sin esperar en pantalla.', 'operacion'),
  ('tramite.lote.reprocesar', 'tramite', 'Reprocesar los errores de una carga masiva', 'Volver a intentar las filas del lote que fallaron.', 'operacion'),
  ('tramite.lote.ver', 'tramite', 'Ver una carga masiva', 'Abrir el detalle de un lote y sus filas.', 'operacion'),
  ('tramite.lote.ver_estado', 'tramite', 'Ver el estado de una carga masiva', 'Consultar por dónde va el proceso del lote.', 'operacion'),
  ('tramite.metricas.ver_gestor', 'tramite', 'Ver las métricas por gestor', 'Consultar el rendimiento de cada gestor de trámites.', 'operacion'),
  ('tramite.metricas.ver_resumen', 'tramite', 'Ver el resumen de métricas', 'Consultar los indicadores agregados de trámites.', 'operacion'),
  ('tramite.motivos_rechazo.ver', 'tramite', 'Ver los motivos de rechazo del organismo', 'Consultar el catálogo de causales de devolución.', 'operacion'),
  ('tramite.notificaciones.ver_config', 'tramite', 'Ver la configuración de notificaciones', 'Consultar qué avisos se envían y a quién.', 'operacion'),
  ('tramite.ocr.descargar', 'tramite', 'Abrir un documento leído por OCR', 'Ver el archivo del que se extrajeron los datos.', 'operacion'),
  ('tramite.ocr.leer', 'tramite', 'Leer un documento con OCR', 'Extraer los datos de un documento escaneado del trámite.', 'operacion'),
  ('tramite.participantes.invitar', 'tramite', 'Invitar a un participante', 'Enviar el enlace para que un tercero aporte sus datos.', 'operacion'),
  ('tramite.participantes.ver_pendientes', 'tramite', 'Ver los participantes pendientes', 'Consultar quién falta por completar su parte.', 'operacion'),
  ('tramite.participantes.verificar_enlace', 'tramite', 'Verificar el enlace de un participante', 'Comprobar que el enlace de invitación sigue siendo válido.', 'operacion'),
  ('tramite.preflight.accionar', 'tramite', 'Accionar sobre un bloqueo de viabilidad', 'Ejecutar la acción que propone el diagnóstico del trámite.', 'operacion'),
  ('tramite.preflight.evaluar', 'tramite', 'Evaluar la viabilidad de un trámite', 'Comprobar antes de radicar si el trámite puede seguir.', 'operacion'),
  ('tramite.preflight.ver', 'tramite', 'Ver la viabilidad de un trámite', 'Consultar los bloqueos detectados en el trámite.', 'operacion'),
  ('tramite.tipologias.ver', 'tramite', 'Ver las tipologías de trámite', 'Consultar el catálogo de tipos de trámite.', 'operacion'),
  ('tramite.tramite.cambiar_estado', 'tramite', 'Cambiar el estado de un trámite', 'Avanzar o retroceder el trámite en su flujo.', 'operacion'),
  ('tramite.tramite.crear', 'tramite', 'Crear un trámite', 'Radicar un trámite de tránsito nuevo.', 'operacion'),
  ('tramite.tramite.editar', 'tramite', 'Editar un trámite', 'Corregir los datos de un trámite en curso.', 'operacion'),
  ('tramite.tramite.rechazar_ot', 'tramite', 'Registrar el rechazo del organismo', 'Anotar que el organismo devolvió el trámite y por qué.', 'operacion'),
  ('tramite.tramite.ver', 'tramite', 'Ver un trámite', 'Abrir el detalle de un trámite de tránsito.', 'operacion'),
  ('tramite.tramite.ver_historial', 'tramite', 'Ver el historial de un trámite', 'Consultar la línea de tiempo del trámite.', 'operacion'),
  ('tramites.autogestion.desbloquear', 'tramites', 'Desbloquear la autogestión del cliente', 'Permitir que el cliente vuelva a radicar por su cuenta.', 'operacion'),
  ('tramites.autogestion.revocar', 'tramites', 'Revocar la autogestión del cliente', 'Quitarle al cliente la posibilidad de radicar por su cuenta.', 'operacion'),
  ('tramites.cola.filtrar', 'tramites', 'Filtrar la cola de trámites FLITO', 'Leer los contadores y las facetas de la bandeja.', 'operacion'),
  ('tramites.cola.ver', 'tramites', 'Ver la cola de trámites FLITO', 'Abrir la bandeja de trámites de SOAT e impuestos.', 'operacion'),
  ('tramites.demo.sembrar', 'tramites', 'Sembrar datos de demostración', 'Crear trámites de ejemplo para mostrar el producto.', 'operacion'),
  ('tramites.empresa.crear', 'tramites', 'Crear una empresa cliente', 'Dar de alta la compañía a la que se le van a radicar trámites.', 'operacion'),
  ('tramites.solicitud.pedir_ambos', 'tramites', 'Solicitar SOAT e impuestos a la vez', 'Radicar los dos trámites del vehículo en una sola operación.', 'operacion'),
  ('tramites.solicitud.pedir_impuestos', 'tramites', 'Solicitar impuestos para un vehículo', 'Radicar un trámite de impuesto vehicular desde Operaciones.', 'operacion'),
  ('tramites.solicitud.pedir_soat', 'tramites', 'Solicitar SOAT para un vehículo', 'Radicar un trámite de SOAT desde Operaciones.', 'operacion'),
  ('tramites.soportes.descargar', 'tramites', 'Descargar soportes de trámites en ZIP', 'Bajar en un solo archivo los soportes de los trámites seleccionados.', 'operacion'),
  ('tramites.tramite.entregar', 'tramites', 'Entregar trámites FLITO', 'Marcar como entregados los trámites seleccionados.', 'operacion'),
  ('tramites.tramite.ver_historial', 'tramites', 'Ver el historial de un trámite FLITO', 'Consultar la línea de tiempo del trámite.', 'operacion'),
  ('tramites.tramite.ver_soportes', 'tramites', 'Ver los soportes de un trámite FLITO', 'Listar y abrir los documentos del trámite.', 'operacion'),
  ('transito.bandeja.ver_pendientes', 'transito', 'Ver los trámites pendientes del organismo', 'Abrir la bandeja de lo que espera gestión en tránsito.', 'operacion'),
  ('transito.bandeja.ver_propios', 'transito', 'Ver mis trámites de tránsito', 'Consultar los trámites que ha tomado el gestor.', 'operacion'),
  ('transito.checklist.editar', 'transito', 'Editar el checklist de un organismo', 'Cambiar la lista de documentos exigidos por tipología.', 'operacion'),
  ('transito.checklist.ver', 'transito', 'Ver el checklist de un organismo', 'Consultar qué documentos exige el organismo por tipología.', 'operacion'),
  ('transito.config.editar', 'transito', 'Editar la configuración de un organismo', 'Cambiar los parámetros de operación del organismo.', 'operacion'),
  ('transito.config.listar', 'transito', 'Ver la configuración de los organismos', 'Consultar cómo está configurado cada organismo de tránsito.', 'operacion'),
  ('transito.config.ver', 'transito', 'Ver la configuración de un organismo', 'Abrir los parámetros de un organismo concreto.', 'operacion'),
  ('transito.logo.borrar', 'transito', 'Quitar el logo de un organismo', 'Retirar la imagen del organismo de los documentos.', 'operacion'),
  ('transito.logo.cargar', 'transito', 'Cargar el logo de un organismo', 'Subir la imagen que se imprime en los documentos del organismo.', 'operacion'),
  ('transito.logo.ver', 'transito', 'Ver el logo de un organismo', 'Abrir la imagen que se imprime en los documentos del organismo.', 'operacion'),
  ('transito.organismos.listar', 'transito', 'Ver los organismos de tránsito', 'Consultar los organismos con los que se opera.', 'operacion'),
  ('transito.placa.asignar', 'transito', 'Asignar la placa de un trámite', 'Registrar la placa que el organismo otorgó.', 'operacion'),
  ('transito.placa.confirmar', 'transito', 'Confirmar la placa de un trámite', 'Dar por buena la placa asignada y cerrar el paso.', 'operacion'),
  ('transito.tramite.tomar', 'transito', 'Tomar un trámite de tránsito', 'Asignarse un trámite pendiente de la bandeja.', 'operacion'),
  ('transito.traspasos.listar', 'transito', 'Ver los traspasos', 'Listar los traspasos en curso ante el organismo.', 'operacion'),
  ('transito.traspasos.ver', 'transito', 'Ver un traspaso', 'Abrir el detalle de un traspaso y sus partes.', 'operacion')
ON CONFLICT (codigo) DO NOTHING;

-- Reparto de partida rol × función (AC4). Generado: no editar a mano.
INSERT INTO permisos_rol_funcion (rol_codigo, funcion_codigo) VALUES
  ('admin', 'bitacora.bitacora.ver'),
  ('admin', 'bitacora.bitacora.ver_recurso'),
  ('admin', 'bolsas.alertas.ver'),
  ('admin', 'bolsas.bolsa.ver'),
  ('admin', 'bolsas.cierre.crear'),
  ('admin', 'bolsas.cierres.ver'),
  ('admin', 'bolsas.consolidado.ver'),
  ('admin', 'bolsas.extracto.descargar'),
  ('admin', 'bolsas.movimiento.corregir'),
  ('admin', 'bolsas.movimiento.registrar'),
  ('admin', 'bolsas.movimientos.ver'),
  ('admin', 'bolsas.recarga.registrar'),
  ('admin', 'bolsas.riesgo.ver'),
  ('admin', 'bolsas.soporte.descargar'),
  ('admin', 'bolsas.transito.cargar'),
  ('admin', 'bolsas.transito.crear'),
  ('admin', 'bolsas.transito.editar'),
  ('admin', 'bolsas.transito.listar'),
  ('admin', 'bolsas.transito.ver'),
  ('admin', 'bolsas.transito.ver_movimientos'),
  ('admin', 'comparendos.causales.crear'),
  ('admin', 'comparendos.causales.editar'),
  ('admin', 'comparendos.causales.listar'),
  ('admin', 'comparendos.municipios.crear'),
  ('admin', 'comparendos.municipios.editar'),
  ('admin', 'comparendos.municipios.listar'),
  ('admin', 'comparendos.nits.borrar'),
  ('admin', 'comparendos.nits.crear'),
  ('admin', 'comparendos.nits.editar'),
  ('admin', 'comparendos.nits.listar'),
  ('admin', 'comparendos.registro.gestionar'),
  ('admin', 'comparendos.registro.ver'),
  ('admin', 'comparendos.registro.ver_eventos'),
  ('admin', 'comparendos.registros.buscar'),
  ('admin', 'comparendos.registros.exportar'),
  ('admin', 'comparendos.registros.listar'),
  ('admin', 'comparendos.simit.guardar_token'),
  ('admin', 'comparendos.simit.ver_token'),
  ('admin', 'comparendos.sync.lanzar'),
  ('admin', 'comparendos.sync.ver_corrida'),
  ('admin', 'comparendos.sync.ver_corridas'),
  ('admin', 'compuerta.cola.ver'),
  ('admin', 'compuerta.tramite.entregar'),
  ('admin', 'compuerta.tramite.ver'),
  ('admin', 'conciliacion.boleta.cargar'),
  ('admin', 'conciliacion.boleta.conciliar'),
  ('admin', 'conciliacion.boleta.descartar'),
  ('admin', 'conciliacion.boleta.recruzar'),
  ('admin', 'conciliacion.boleta.ver'),
  ('admin', 'conciliacion.boletas.listar'),
  ('admin', 'conciliacion.comprobante.cargar'),
  ('admin', 'conciliacion.comprobante.descargar'),
  ('admin', 'conciliacion.comprobante.reemplazar'),
  ('admin', 'derechos.candidatos.ver'),
  ('admin', 'derechos.cola.filtrar'),
  ('admin', 'derechos.cola.ver'),
  ('admin', 'derechos.drive.listar'),
  ('admin', 'derechos.drive.procesar'),
  ('admin', 'derechos.drive.ver_registro'),
  ('admin', 'derechos.recibos.cargar'),
  ('admin', 'derechos.soporte.descargar'),
  ('admin', 'impuestos.certificado.descargar'),
  ('admin', 'impuestos.cola.filtrar'),
  ('admin', 'impuestos.cola.ver'),
  ('admin', 'impuestos.excel.exportar'),
  ('admin', 'impuestos.factura.ver'),
  ('admin', 'impuestos.recibos.cargar'),
  ('admin', 'impuestos.soportes.descargar'),
  ('admin', 'impuestos.tramite.certificar'),
  ('admin', 'impuestos.tramite.certificar_lote'),
  ('admin', 'impuestos.tramite.enviar'),
  ('admin', 'impuestos.tramite.reactivar'),
  ('admin', 'impuestos.tramite.rechazar'),
  ('admin', 'impuestos.tramite.reversar'),
  ('admin', 'impuestos.tramite.ver'),
  ('admin', 'impuestos.tramite.ver_historial'),
  ('admin', 'impuestos.tramite.ver_soportes'),
  ('admin', 'liquidacion.liquidacion.facturar'),
  ('admin', 'liquidacion.liquidacion.liquidar'),
  ('admin', 'liquidacion.liquidacion.liquidar_lote'),
  ('admin', 'liquidacion.liquidacion.reversar'),
  ('admin', 'liquidacion.liquidacion.ver'),
  ('admin', 'liquidacion.liquidacion.ver_eventos'),
  ('admin', 'logistica.actas.descargar'),
  ('admin', 'logistica.actas.despachar'),
  ('admin', 'logistica.actas.devolver'),
  ('admin', 'logistica.actas.entregar'),
  ('admin', 'logistica.actas.listar'),
  ('admin', 'logistica.actas.ver'),
  ('admin', 'logistica.consola.filtrar'),
  ('admin', 'logistica.consola.ver'),
  ('admin', 'logistica.documento.escanear'),
  ('admin', 'logistica.documento.reportar_novedad'),
  ('admin', 'logistica.documento.reversar'),
  ('admin', 'logistica.documento.ver'),
  ('admin', 'logistica.lote.cerrar'),
  ('admin', 'logistica.lt.validar'),
  ('admin', 'logistica.ruta.ver'),
  ('admin', 'pagina.clients'),
  ('admin', 'pagina.dashboard'),
  ('admin', 'pagina.drive'),
  ('admin', 'pagina.finanzas_reporte_costos'),
  ('admin', 'pagina.fleet'),
  ('admin', 'pagina.flito_bitacora'),
  ('admin', 'pagina.flito_bolsas'),
  ('admin', 'pagina.flito_comparendos'),
  ('admin', 'pagina.flito_compuerta'),
  ('admin', 'pagina.flito_conciliacion'),
  ('admin', 'pagina.flito_derechos'),
  ('admin', 'pagina.flito_impuestos'),
  ('admin', 'pagina.flito_logistica'),
  ('admin', 'pagina.flito_logistica_ruta'),
  ('admin', 'pagina.flito_revisiones'),
  ('admin', 'pagina.flito_soat'),
  ('admin', 'pagina.flito_tablero'),
  ('admin', 'pagina.flito_tramites'),
  ('admin', 'pagina.laft'),
  ('admin', 'pagina.laft_audit_plan'),
  ('admin', 'pagina.laft_dashboard'),
  ('admin', 'pagina.laft_manual'),
  ('admin', 'pagina.laft_oficial'),
  ('admin', 'pagina.laft_trainings'),
  ('admin', 'pagina.laft_unusual'),
  ('admin', 'pagina.maintenance'),
  ('admin', 'pagina.pesv'),
  ('admin', 'pagina.pesv_normativa'),
  ('admin', 'pagina.pesv_raci'),
  ('admin', 'pagina.pesv_retencion'),
  ('admin', 'pagina.privacy'),
  ('admin', 'pagina.rndc'),
  ('admin', 'pagina.rndc_admin'),
  ('admin', 'pagina.siigo_credenciales'),
  ('admin', 'pagina.siigo_operacion'),
  ('admin', 'pagina.siigo_parametrizacion'),
  ('admin', 'pagina.soat'),
  ('admin', 'pagina.tax_reader'),
  ('admin', 'pagina.tramite'),
  ('admin', 'pagina.transito'),
  ('admin', 'pagina.transito_organismos'),
  ('admin', 'pagina.users'),
  ('admin', 'pagina.vehicles'),
  ('admin', 'parametrizacion.companias.editar'),
  ('admin', 'parametrizacion.companias.listar'),
  ('admin', 'parametrizacion.organismos.editar'),
  ('admin', 'parametrizacion.organismos.fijar_modalidad'),
  ('admin', 'parametrizacion.organismos.listar'),
  ('admin', 'parametrizacion.organismos.ver_vigencias'),
  ('admin', 'parametrizacion.proveedores.crear'),
  ('admin', 'parametrizacion.proveedores.editar'),
  ('admin', 'parametrizacion.proveedores.listar'),
  ('admin', 'parametrizacion.tarifas.borrar'),
  ('admin', 'parametrizacion.tarifas.crear'),
  ('admin', 'parametrizacion.tarifas.editar'),
  ('admin', 'parametrizacion.tarifas.listar'),
  ('admin', 'revisiones.campos.ver'),
  ('admin', 'revisiones.cola.ver'),
  ('admin', 'revisiones.revision.descartar'),
  ('admin', 'revisiones.revision.resolver'),
  ('admin', 'revisiones.soporte.descargar'),
  ('admin', 'soat.cola.filtrar'),
  ('admin', 'soat.cola.ver'),
  ('admin', 'soat.comprobante.cargar'),
  ('admin', 'soat.excel.exportar'),
  ('admin', 'soat.masiva.cargar'),
  ('admin', 'soat.proveedor.cambiar'),
  ('admin', 'soat.solicitud.asumir'),
  ('admin', 'soat.solicitud.devolver'),
  ('admin', 'soat.solicitud.enviar'),
  ('admin', 'soat.solicitud.reactivar'),
  ('admin', 'soat.solicitud.rechazar'),
  ('admin', 'soat.solicitud.reversar'),
  ('admin', 'soat.solicitud.ver'),
  ('admin', 'soat.solicitud.ver_historial'),
  ('admin', 'soat.solicitud.ver_soportes'),
  ('admin', 'soat.soportes.descargar'),
  ('admin', 'sync.sync.lanzar'),
  ('admin', 'sync.sync.ver_estado'),
  ('admin', 'tablero.tablero.ver'),
  ('admin', 'tramite.checklist.sugerir'),
  ('admin', 'tramite.checklist.ver'),
  ('admin', 'tramite.cola.ver'),
  ('admin', 'tramite.contrato.generar'),
  ('admin', 'tramite.documentos.borrar'),
  ('admin', 'tramite.documentos.cargar'),
  ('admin', 'tramite.documentos.descargar'),
  ('admin', 'tramite.documentos.listar'),
  ('admin', 'tramite.embudo.ver'),
  ('admin', 'tramite.estadisticas.ver_metricas'),
  ('admin', 'tramite.estadisticas.ver_resumen'),
  ('admin', 'tramite.expediente.descargar'),
  ('admin', 'tramite.fur.generar'),
  ('admin', 'tramite.identidad.certificar'),
  ('admin', 'tramite.identidad.iniciar'),
  ('admin', 'tramite.identidad.iniciar_partes'),
  ('admin', 'tramite.identidad.seguir'),
  ('admin', 'tramite.identidad.ver_documentos'),
  ('admin', 'tramite.identidad.ver_estado'),
  ('admin', 'tramite.improntas.generar'),
  ('admin', 'tramite.impuesto.consultar'),
  ('admin', 'tramite.lote.confirmar'),
  ('admin', 'tramite.lote.crear'),
  ('admin', 'tramite.lote.descargar_plantilla'),
  ('admin', 'tramite.lote.descargar_resultados'),
  ('admin', 'tramite.lote.listar'),
  ('admin', 'tramite.lote.previsualizar'),
  ('admin', 'tramite.lote.procesar_async'),
  ('admin', 'tramite.lote.reprocesar'),
  ('admin', 'tramite.lote.ver'),
  ('admin', 'tramite.lote.ver_estado'),
  ('admin', 'tramite.metricas.ver_gestor'),
  ('admin', 'tramite.metricas.ver_resumen'),
  ('admin', 'tramite.motivos_rechazo.ver'),
  ('admin', 'tramite.notificaciones.ver_config'),
  ('admin', 'tramite.ocr.descargar'),
  ('admin', 'tramite.ocr.leer'),
  ('admin', 'tramite.participantes.invitar'),
  ('admin', 'tramite.participantes.ver_pendientes'),
  ('admin', 'tramite.participantes.verificar_enlace'),
  ('admin', 'tramite.preflight.accionar'),
  ('admin', 'tramite.preflight.evaluar'),
  ('admin', 'tramite.preflight.ver'),
  ('admin', 'tramite.tipologias.ver'),
  ('admin', 'tramite.tramite.cambiar_estado'),
  ('admin', 'tramite.tramite.crear'),
  ('admin', 'tramite.tramite.editar'),
  ('admin', 'tramite.tramite.rechazar_ot'),
  ('admin', 'tramite.tramite.ver'),
  ('admin', 'tramite.tramite.ver_historial'),
  ('admin', 'tramites.autogestion.desbloquear'),
  ('admin', 'tramites.autogestion.revocar'),
  ('admin', 'tramites.cola.filtrar'),
  ('admin', 'tramites.cola.ver'),
  ('admin', 'tramites.demo.sembrar'),
  ('admin', 'tramites.empresa.crear'),
  ('admin', 'tramites.solicitud.pedir_ambos'),
  ('admin', 'tramites.solicitud.pedir_impuestos'),
  ('admin', 'tramites.solicitud.pedir_soat'),
  ('admin', 'tramites.soportes.descargar'),
  ('admin', 'tramites.tramite.entregar'),
  ('admin', 'tramites.tramite.ver_historial'),
  ('admin', 'tramites.tramite.ver_soportes'),
  ('admin', 'transito.bandeja.ver_pendientes'),
  ('admin', 'transito.bandeja.ver_propios'),
  ('admin', 'transito.checklist.editar'),
  ('admin', 'transito.checklist.ver'),
  ('admin', 'transito.config.editar'),
  ('admin', 'transito.config.listar'),
  ('admin', 'transito.config.ver'),
  ('admin', 'transito.logo.borrar'),
  ('admin', 'transito.logo.cargar'),
  ('admin', 'transito.logo.ver'),
  ('admin', 'transito.organismos.listar'),
  ('admin', 'transito.placa.asignar'),
  ('admin', 'transito.placa.confirmar'),
  ('admin', 'transito.tramite.tomar'),
  ('admin', 'transito.traspasos.listar'),
  ('admin', 'transito.traspasos.ver'),
  ('auditor', 'bitacora.bitacora.ver'),
  ('auditor', 'bitacora.bitacora.ver_recurso'),
  ('auditor', 'compuerta.cola.ver'),
  ('auditor', 'compuerta.tramite.ver'),
  ('auditor', 'derechos.candidatos.ver'),
  ('auditor', 'derechos.cola.filtrar'),
  ('auditor', 'derechos.cola.ver'),
  ('auditor', 'derechos.drive.listar'),
  ('auditor', 'derechos.drive.ver_registro'),
  ('auditor', 'derechos.soporte.descargar'),
  ('auditor', 'impuestos.cola.filtrar'),
  ('auditor', 'impuestos.cola.ver'),
  ('auditor', 'impuestos.tramite.ver'),
  ('auditor', 'impuestos.tramite.ver_historial'),
  ('auditor', 'impuestos.tramite.ver_soportes'),
  ('auditor', 'liquidacion.liquidacion.ver'),
  ('auditor', 'liquidacion.liquidacion.ver_eventos'),
  ('auditor', 'logistica.actas.descargar'),
  ('auditor', 'logistica.actas.listar'),
  ('auditor', 'logistica.actas.ver'),
  ('auditor', 'logistica.consola.filtrar'),
  ('auditor', 'logistica.consola.ver'),
  ('auditor', 'logistica.documento.ver'),
  ('auditor', 'pagina.clients'),
  ('auditor', 'pagina.dashboard'),
  ('auditor', 'pagina.finanzas_reporte_costos'),
  ('auditor', 'pagina.flito_bitacora'),
  ('auditor', 'pagina.flito_compuerta'),
  ('auditor', 'pagina.flito_derechos'),
  ('auditor', 'pagina.flito_impuestos'),
  ('auditor', 'pagina.flito_logistica'),
  ('auditor', 'pagina.flito_revisiones'),
  ('auditor', 'pagina.flito_soat'),
  ('auditor', 'pagina.flito_tablero'),
  ('auditor', 'pagina.flito_tramites'),
  ('auditor', 'pagina.laft_audit_plan'),
  ('auditor', 'pagina.laft_dashboard'),
  ('auditor', 'pagina.laft_manual'),
  ('auditor', 'pagina.laft_oficial'),
  ('auditor', 'pagina.siigo_operacion'),
  ('auditor', 'pagina.siigo_parametrizacion'),
  ('auditor', 'pagina.soat'),
  ('auditor', 'parametrizacion.companias.listar'),
  ('auditor', 'parametrizacion.organismos.listar'),
  ('auditor', 'parametrizacion.organismos.ver_vigencias'),
  ('auditor', 'parametrizacion.proveedores.listar'),
  ('auditor', 'parametrizacion.tarifas.listar'),
  ('auditor', 'revisiones.campos.ver'),
  ('auditor', 'revisiones.cola.ver'),
  ('auditor', 'revisiones.soporte.descargar'),
  ('auditor', 'soat.cola.filtrar'),
  ('auditor', 'soat.cola.ver'),
  ('auditor', 'soat.solicitud.ver'),
  ('auditor', 'soat.solicitud.ver_historial'),
  ('auditor', 'soat.solicitud.ver_soportes'),
  ('auditor', 'tablero.tablero.ver'),
  ('auditor', 'tramites.cola.filtrar'),
  ('auditor', 'tramites.cola.ver'),
  ('auditor', 'tramites.tramite.ver_historial'),
  ('auditor', 'tramites.tramite.ver_soportes'),
  ('cliente', 'pagina.flito_soat'),
  ('cliente', 'soat.cola.filtrar'),
  ('cliente', 'soat.cola.ver'),
  ('cliente', 'soat.factura.leer'),
  ('cliente', 'soat.runt.preconsultar'),
  ('cliente', 'soat.solicitud.crear'),
  ('cliente', 'soat.solicitud.ver'),
  ('cliente', 'soat.solicitud.ver_historial'),
  ('cliente', 'soat.solicitud.ver_soportes'),
  ('compliance', 'pagina.dashboard'),
  ('compliance', 'pagina.laft'),
  ('compliance', 'pagina.laft_audit_plan'),
  ('compliance', 'pagina.laft_dashboard'),
  ('compliance', 'pagina.laft_manual'),
  ('compliance', 'pagina.laft_oficial'),
  ('compliance', 'pagina.laft_trainings'),
  ('compliance', 'pagina.laft_unusual'),
  ('compliance', 'pagina.pesv'),
  ('compliance', 'pagina.pesv_normativa'),
  ('compliance', 'pagina.pesv_raci'),
  ('compliance', 'pagina.pesv_retencion'),
  ('compliance', 'pagina.privacy'),
  ('conductor', 'pagina.dashboard'),
  ('conductor', 'pagina.pesv'),
  ('financiera', 'bolsas.alertas.ver'),
  ('financiera', 'bolsas.bolsa.ver'),
  ('financiera', 'bolsas.cierre.crear'),
  ('financiera', 'bolsas.cierres.ver'),
  ('financiera', 'bolsas.consolidado.ver'),
  ('financiera', 'bolsas.extracto.descargar'),
  ('financiera', 'bolsas.movimiento.corregir'),
  ('financiera', 'bolsas.movimiento.registrar'),
  ('financiera', 'bolsas.movimientos.ver'),
  ('financiera', 'bolsas.recarga.registrar'),
  ('financiera', 'bolsas.riesgo.ver'),
  ('financiera', 'bolsas.soporte.descargar'),
  ('financiera', 'bolsas.transito.cargar'),
  ('financiera', 'bolsas.transito.crear'),
  ('financiera', 'bolsas.transito.editar'),
  ('financiera', 'bolsas.transito.listar'),
  ('financiera', 'bolsas.transito.ver'),
  ('financiera', 'bolsas.transito.ver_movimientos'),
  ('financiera', 'conciliacion.boleta.cargar'),
  ('financiera', 'conciliacion.boleta.conciliar'),
  ('financiera', 'conciliacion.boleta.descartar'),
  ('financiera', 'conciliacion.boleta.recruzar'),
  ('financiera', 'conciliacion.boleta.ver'),
  ('financiera', 'conciliacion.boletas.listar'),
  ('financiera', 'conciliacion.comprobante.cargar'),
  ('financiera', 'conciliacion.comprobante.descargar'),
  ('financiera', 'conciliacion.comprobante.reemplazar'),
  ('financiera', 'liquidacion.liquidacion.facturar'),
  ('financiera', 'liquidacion.liquidacion.liquidar'),
  ('financiera', 'liquidacion.liquidacion.liquidar_lote'),
  ('financiera', 'liquidacion.liquidacion.ver'),
  ('financiera', 'liquidacion.liquidacion.ver_eventos'),
  ('financiera', 'pagina.clients'),
  ('financiera', 'pagina.dashboard'),
  ('financiera', 'pagina.finanzas_reporte_costos'),
  ('financiera', 'pagina.flito_bolsas'),
  ('financiera', 'pagina.flito_conciliacion'),
  ('financiera', 'pagina.siigo_operacion'),
  ('financiera', 'pagina.siigo_parametrizacion'),
  ('financiera', 'parametrizacion.tarifas.borrar'),
  ('financiera', 'parametrizacion.tarifas.crear'),
  ('financiera', 'parametrizacion.tarifas.editar'),
  ('financiera', 'parametrizacion.tarifas.listar'),
  ('gestor_impuestos', 'impuestos.certificado.descargar'),
  ('gestor_impuestos', 'impuestos.cola.filtrar'),
  ('gestor_impuestos', 'impuestos.cola.ver'),
  ('gestor_impuestos', 'impuestos.excel.exportar'),
  ('gestor_impuestos', 'impuestos.factura.ver'),
  ('gestor_impuestos', 'impuestos.recibos.cargar'),
  ('gestor_impuestos', 'impuestos.soportes.descargar'),
  ('gestor_impuestos', 'impuestos.tramite.certificar'),
  ('gestor_impuestos', 'impuestos.tramite.certificar_lote'),
  ('gestor_impuestos', 'impuestos.tramite.rechazar'),
  ('gestor_impuestos', 'impuestos.tramite.ver'),
  ('gestor_impuestos', 'impuestos.tramite.ver_historial'),
  ('gestor_impuestos', 'impuestos.tramite.ver_soportes'),
  ('gestor_impuestos', 'pagina.dashboard'),
  ('gestor_impuestos', 'pagina.flito_impuestos'),
  ('lider_pesv', 'pagina.dashboard'),
  ('lider_pesv', 'pagina.fleet'),
  ('lider_pesv', 'pagina.maintenance'),
  ('lider_pesv', 'pagina.pesv'),
  ('lider_pesv', 'pagina.pesv_normativa'),
  ('lider_pesv', 'pagina.pesv_raci'),
  ('lider_pesv', 'pagina.pesv_retencion'),
  ('mensajero', 'logistica.actas.devolver'),
  ('mensajero', 'logistica.actas.entregar'),
  ('mensajero', 'logistica.documento.escanear'),
  ('mensajero', 'logistica.documento.reportar_novedad'),
  ('mensajero', 'logistica.lt.validar'),
  ('mensajero', 'logistica.ruta.ver'),
  ('mensajero', 'pagina.dashboard'),
  ('mensajero', 'pagina.flito_logistica_ruta'),
  ('proveedor', 'pagina.dashboard'),
  ('proveedor', 'pagina.flito_soat'),
  ('proveedor', 'pagina.soat'),
  ('proveedor', 'soat.cola.filtrar'),
  ('proveedor', 'soat.cola.ver'),
  ('proveedor', 'soat.comprobante.cargar'),
  ('proveedor', 'soat.excel.exportar'),
  ('proveedor', 'soat.masiva.cargar'),
  ('proveedor', 'soat.solicitud.rechazar'),
  ('proveedor', 'soat.solicitud.ver'),
  ('proveedor', 'soat.solicitud.ver_historial'),
  ('proveedor', 'soat.solicitud.ver_soportes'),
  ('proveedor', 'soat.soportes.descargar'),
  ('supervisor_flota', 'pagina.dashboard'),
  ('supervisor_flota', 'pagina.fleet'),
  ('supervisor_flota', 'pagina.maintenance'),
  ('supervisor_flota', 'pagina.pesv'),
  ('supervisor_flota', 'pagina.vehicles'),
  ('transito', 'pagina.dashboard'),
  ('transito', 'pagina.transito'),
  ('transito', 'tramite.checklist.sugerir'),
  ('transito', 'tramite.checklist.ver'),
  ('transito', 'tramite.cola.ver'),
  ('transito', 'tramite.contrato.generar'),
  ('transito', 'tramite.documentos.borrar'),
  ('transito', 'tramite.documentos.cargar'),
  ('transito', 'tramite.documentos.descargar'),
  ('transito', 'tramite.documentos.listar'),
  ('transito', 'tramite.embudo.ver'),
  ('transito', 'tramite.estadisticas.ver_metricas'),
  ('transito', 'tramite.estadisticas.ver_resumen'),
  ('transito', 'tramite.expediente.descargar'),
  ('transito', 'tramite.fur.generar'),
  ('transito', 'tramite.improntas.generar'),
  ('transito', 'tramite.impuesto.consultar'),
  ('transito', 'tramite.lote.confirmar'),
  ('transito', 'tramite.lote.crear'),
  ('transito', 'tramite.lote.descargar_plantilla'),
  ('transito', 'tramite.lote.listar'),
  ('transito', 'tramite.lote.previsualizar'),
  ('transito', 'tramite.lote.procesar_async'),
  ('transito', 'tramite.lote.ver'),
  ('transito', 'tramite.lote.ver_estado'),
  ('transito', 'tramite.metricas.ver_gestor'),
  ('transito', 'tramite.motivos_rechazo.ver'),
  ('transito', 'tramite.notificaciones.ver_config'),
  ('transito', 'tramite.participantes.invitar'),
  ('transito', 'tramite.participantes.ver_pendientes'),
  ('transito', 'tramite.participantes.verificar_enlace'),
  ('transito', 'tramite.preflight.accionar'),
  ('transito', 'tramite.preflight.evaluar'),
  ('transito', 'tramite.preflight.ver'),
  ('transito', 'tramite.tipologias.ver'),
  ('transito', 'tramite.tramite.cambiar_estado'),
  ('transito', 'tramite.tramite.crear'),
  ('transito', 'tramite.tramite.editar'),
  ('transito', 'tramite.tramite.rechazar_ot'),
  ('transito', 'tramite.tramite.ver'),
  ('transito', 'tramite.tramite.ver_historial'),
  ('transito', 'transito.bandeja.ver_pendientes'),
  ('transito', 'transito.bandeja.ver_propios'),
  ('transito', 'transito.checklist.ver'),
  ('transito', 'transito.config.ver'),
  ('transito', 'transito.logo.ver'),
  ('transito', 'transito.organismos.listar'),
  ('transito', 'transito.placa.asignar'),
  ('transito', 'transito.placa.confirmar'),
  ('transito', 'transito.tramite.tomar'),
  ('transito', 'transito.traspasos.listar'),
  ('transito', 'transito.traspasos.ver')
ON CONFLICT (rol_codigo, funcion_codigo) DO NOTHING;
-- ── FIN DEL SEED GENERADO ───────────────────────────────────────────────────────────────────────

-- ── Paso 5 — Backfill de los permisos por usuario (AC4) ─────────────────────────────────────────
-- Una fila ('conceder', pagina.<slug>) por cada entrada VALIDA de users.allowed_pages.
--
-- «Valida» es el EXISTS contra el catalogo, y hace dos trabajos a la vez: descarta los slugs que ya
-- no existen (los que `isValidPage` filtra hoy en getEffectivePages, que por eso nunca concedian
-- nada) y descarta `flito_ayuda` si alguien lo tuviera escrito a mano — no es concedible, asi que
-- sembrarlo crearia una casilla que miente. Sin el EXISTS esto reventaria con un 23503, que es la
-- otra forma de decir lo mismo pero a mitad de la migracion.
--
-- DISTINCT y no solo ON CONFLICT: un `allowed_pages` con el mismo slug repetido produciria dos filas
-- identicas en la MISMA sentencia, y eso el ON CONFLICT no lo tapa.
--
-- OJO, y hay que saberlo antes de tocar nada: esta tabla se SIEMBRA aqui y NO LA LEE NADIE todavia.
-- El alta y la edicion de usuarios siguen escribiendo `users.allowed_pages` (users.routes.ts:381 y
-- :503), y de ahi es de donde `paginasEfectivasDeUsuario` toma las paginas propias de cada usuario.
-- Es deliberado: leer esta tabla sin haber movido el camino de ESCRITURA congelaria los permisos por
-- usuario en la foto de hoy — el administrador concederia una pagina, la columna cambiaria y el
-- usuario no veria nada distinto. Lo que esta HU SI enciende es la mitad del ROL
-- (`permisos_rol_funcion`), que es la que repone las paginas de `admin` al retirar sus dos atajos.
-- Las dos mitades se juntan en la HU de permisos por usuario, que es tambien quien estrena `revocar`.
INSERT INTO permisos_usuario_funcion (user_id, funcion_codigo, efecto)
SELECT DISTINCT u.id, 'pagina.' || s.slug, 'conceder'
  FROM users u
  CROSS JOIN LATERAL unnest(u.allowed_pages) AS s(slug)
 WHERE EXISTS (SELECT 1 FROM permisos_funciones f WHERE f.codigo = 'pagina.' || s.slug)
ON CONFLICT (user_id, funcion_codigo) DO NOTHING;

-- ── Paso 6 — La cuenta, en el log del CD ────────────────────────────────────────────────────────
-- No es telemetria: es lo que permite leer en el log del despliegue si el reparto llego entero, y en
-- particular si `admin` quedo con TODAS sus funciones. Los dos atajos cableados que hoy le dan todo
-- (getEffectivePages y la fila admin de ROLE_DEFAULT_PAGES) se retiran en el mismo PR que esta
-- migracion: si estas marcas no estan, el administrador se queda sin una sola pantalla.
DO $resumen$
DECLARE
  n_funciones int; n_reparto int; n_admin int; n_usuario int; n_revocar int;
BEGIN
  SELECT count(*) INTO n_funciones FROM permisos_funciones;
  SELECT count(*) INTO n_reparto   FROM permisos_rol_funcion;
  SELECT count(*) INTO n_admin     FROM permisos_rol_funcion WHERE rol_codigo = 'admin';
  SELECT count(*) INTO n_usuario   FROM permisos_usuario_funcion;
  SELECT count(*) INTO n_revocar   FROM permisos_usuario_funcion WHERE efecto = 'revocar';
  IF n_admin = 0 THEN
    RAISE EXCEPTION '0179: el rol admin quedo sin ninguna funcion — retirar los atajos lo dejaria sin pantallas';
  END IF;
  IF n_revocar > 0 THEN
    RAISE EXCEPTION '0179: hay % filas con efecto revocar y esta HU no siembra ninguna', n_revocar;
  END IF;
  RAISE NOTICE '0179: % funciones, % filas de reparto (% de admin), % permisos por usuario',
    n_funciones, n_reparto, n_admin, n_usuario;
END $resumen$;
